### ISSUE TITLE
Passthrough - Can't use PF with vfio-pci driver

### ISSUE THREAD

**Issue by sseetharaman6** [k8snetworkplumbingwg/sriov-network-device-plugin#153]
I am using SRIOV DP with Kubevirt for spinning up VMs with SRIOV/Passthrough PCI device. As of Kubevirt v0.19.0, we have to swap the PF and VF drivers from `netdevice` to `vfio-pci` during configuration. This is my configMap:   
```
{
                "resourceName": "pt",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["1528"],
                    "drivers": ["vfio-pci"],
                    "pfNames": ["enp129s0f1"]
                }
            }
```
However, currently DP assumes PF is with network driver. So upon swapping driver to `vfio-pci`, the `discoverHostDevices` routine in SRIOV DP can't query the PF's network information (interface name etc) / can't read the device anymore and therefore can't advertise the resource. 
From DP pod logs:
``` discoverDevices() error adding new device: "open /sys/bus/pci/devices/0000:81:00.1/net: no such file or directory" ```

**Comment by zshi-redhat** [comment]
Hi @sseetharaman6 , sriov device plugin doesn't support advertising PF as a resource and it relies on PF to be in kernel mode in order to discover VFs. In above failure, it looks like PF is bind to dpdk driver(vfio-pci), so accessing to PF sysfs failed.

**Comment by sseetharaman6** [comment]
Yes, but the device plugin can be extended to support passthrough if it can advertise PF as a resource.

**Comment by matrohon** [comment]
I have exactly the same issue when I want the dp to advertise a phisical nic with a virtio driver.

**Comment by sseetharaman6** [comment]
To add more context - it is possible to advertise PF as a resource when it is bound to `netdevice` driver using the SRIOV DP, but if the driver is swapped to `vfio-pci`  or anything else, the DP can't read the sysfs path and errors out

**Comment by booxter** [comment]
@sseetharaman6 from my perspective, it makes sense that the DP would support advertising PF as a single VFIO resource if the same is possible for kernel space registered PF.

**Comment by sseetharaman6** [comment]
@booxter  I agree

**Comment by martinkennelly** [comment]
Closing due to being stale.
