### ISSUE TITLE
Define Project Scope

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-network-device-plugin#215]
With the direction of supporting additional SR-IOV devices(#208, #214 ) I think it's important to lay down some ground rules to make sure the project does not slowly diverge to an undesired direction. I suggest we add a “Project Scope” section under README.md to say what this project should and should not handle. Divergence from the defined rules should be done knowingly and after discussion.

**Comment by adrianchiris** [comment]
#208, #212, #214,

**Comment by ahalim-intel** [comment]
I like this idea. Perhaps, do you a draft or something that you could share?

**Comment by adrianchiris** [comment]
Let's discuss on next meeting, as this IMO should be addressed as part of the work on #208

**Comment by adrianchiris** [comment]
Writing down some of my thoughts on the matter to kick start the process:

- Selectors shall not contain any hardcoded vendor specific non-standard logic. The selection logic must be generic.
As a note: The data on which this logic operates can have a vendor specific nature.
e.g:
*OK*: Have a selector that ensures the existence of a driver file which name is provided in config file.
*Not OK*: have a selector that matches on vendor specific driver file in a hardcoded manner.
*OK*: Have a selector that runs a Hook (specified in config file) that returns `true`/`false` given the PCI device address
*Not OK*: have a selector that runs vendor specific tooling
	
- Determining Mounts, DeviceSpecs, Environment Variables (e.g by `ResourcePools`, `InfoProviders`, `DeviceProviders`) shall be done by a vendor agnostic logic.
Should a vendor specific logic be required, A "hooks" or "plugin" mechanism may be introduced in the future to allow customized logic to be applied for a PCI device / PCI device driver returning the required  Mounts, DeviceSpecs, Environment Variables.

**Comment by amorenoz** [comment]
I'd like to raise a question here about the future of the project with regards to other device slicing technologies such as Intel's Scalable IOV or Mellanox's subfunctions.
Do you envision adding support for these technologies alongside SR-IOV?

**Comment by adrianchiris** [comment]
So i think the high level scope is defined by the governance doc of k8snpwg and this can be closed.

**Comment by martinkennelly** [comment]
See previous comment. Closed.
