### ISSUE TITLE
Unable to set Default route in  pods with static IP created in CRD Network Attachement 

### ISSUE THREAD

**Issue by tunicashashi** [k8snetworkplumbingwg/sriov-network-device-plugin#222]
Hi, May be I am new to this SRIOV-Multus world, so this question could be begginer question. But please have a look.

I want to run pods attached to the SRIOV VFs created with sriov network type. As shown in the below YAML.

### What did you expect to happen?
-Pod should be running

### What are the minimal steps needed to reproduce the bug?
= Run static networks and testpod yaml.

### Anything else we need to know?

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<Input Version Here>|
|SR-IOV CNI Plugin            |<Input Version Here>|
|Multus                       ||
|Kubernetes                   |1.16| 
|OS                           |CentOS 7- StarlingX Host OS|

###Files
##### SR-IOV Network Custom Resource Definition

CRD Files to create NetworkAttachmentDefinition.
....
Static CRD:
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/pci_sriov_net_physnet134f0
spec:
  config: '{
       "type": "sriov",
       "name": "sriov-network",
           "ipam": {
                                "type": "static",
                                "addresses": [
                                                {
                                                        "address": "10.127.53.71/24",
                                                        "gateway": "10.127.53.65"
                                                }

                                                                                               }
                    ],
                "routes": [
                    { "dst": "0.0.0.0/0" },
                    { "dst": "10.127.53.0/24", "gw": "10.127.53.65" }

                ],
            },
   }

.........
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  namespace: sriov-data
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/pci_sriov_net_physnet134f0
spec:
  config: '{
       "type": "sriov",
       "name": "sriov-network",
       "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "10.127.53.0/24",
                         "rangeStart": "10.127.53.71",
                         "rangeEnd": "10.127.53.73",
                         "routes": [
                                { "dst": "0.0.0.0/0" }
                                ],
                         "gateway": "10.127.53.65"
                    } ]
                ]
             }
     }
......
<< pod-tc1.yaml>>

apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  namespace : sriov-data
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{
      "name": "sriov-net1",
      "default-route": ["10.127.53.65"]
    }]'
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/pci_sriov_net_physnet134f0: '1'
      limits:
        intel.com/pci_sriov_net_physnet134f0: '1'
..............

.

When I use "host-local" IPAM, I get the pod created and IP is assigned as:

controller-0:~/sriov_multus$ kubectl apply -f pod-tc1.yaml
pod/testpod1 created
controller-0:~/sriov_multus$  kubectl exec -it testpod1 -n sriov-data -- ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
4: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
6: eth0@if5751: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 66:02:fb:64:ae:fd brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.16.192.172/32 scope global eth0
       valid_lft forever preferred_lft forever
11: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 92:38:70:02:24:87 brd ff:ff:ff:ff:ff:ff
    inet 10.127.53.71/24 brd 10.127.53.255 scope global net1
       valid_lft forever preferred_lft forever
.......................

BUT not when I use IPAM Type= "local" as mentioned in the 1st CRD. I get issue for the pods as below:

controller-0:~/sriov_multus$ kubectl describe pods testpod1 -n sriov-data
Name:         testpod1
Namespace:    sriov-data
Priority:     0
Node:         controller-0/192.168.204.2
Start Time:   Tue, 07 Apr 2020 17:47:16 +0000
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/networks: [{ "name": "sriov-net1", "default-route": ["10.127.53.65"] }]
              k8s.v1.cni.cncf.io/networks-status:
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"k8s.v1.cni.cncf.io/networks":"[{ \"name\": \"sriov-net1\", \"default-route\": ...
Status:       Pending
IP:
IPs:          <none>
Containers:
  appcntr1:
    Container ID:
    Image:         centos/tools
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      --
    Args:
      while true; do sleep 300000; done;
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      intel.com/pci_sriov_net_physnet134f0:  1
    Requests:
      intel.com/pci_sriov_net_physnet134f0:  1
    Environment:                             <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gj4fw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-gj4fw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gj4fw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 30s
                 node.kubernetes.io/unreachable:NoExecute for 30s
Events:
  Type     Reason                  Age        From                   Message
  ----     ------                  ----       ----                   -------
  Normal   Scheduled               <unknown>  default-scheduler      Successfully assigned sriov-data/testpod1 to controller-0
  Warning  FailedCreatePodSandBox  7s         kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "9fb0e5047b7b13f50b99f3612d2a665f6d7c8fe9cd6bd05f9130d57da593f235" network for pod "testpod1": networkPlugin cni failed to set up pod "testpod1_sriov-data" network: Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: GetPodNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: the server could not find the requested resource
  Normal   SandboxChanged          7s         kubelet, controller-0  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  0s         kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3ebdc273efa98dcdc9aba731552ce55f21fe5d624437c73e6911c9ff250bc9a5" network for pod "testpod1": networkPlugin cni failed to set up pod "testpod1_sriov-data" network: Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: GetPodNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: the server could not find the requested resource

What could be the reason behind it?  This subnet is connected through the Interface which has the SRIOV enabled. Is "Static" IPAM supported through SRIOV+Multus.

##### Kubernetes deployment type =  Kubeadm 

O/p of /etc/cni/multus/

{
  "name": "multus-cni-network",
  "type": "multus",
  "cniVersion": "0.3.1",
  "capabilities": {
      "portMappings": true
  },
  "delegates": [
    {
      "cniVersion": "0.3.1",
      "name": "chain",
      "plugins": [
        {
          "cniVersion": "0.3.1",
          "name": "k8s-pod-network",
          "type": "calico",
          "masterplugin": true,
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "controller-0",
          "mtu": 1500,
          "ipam": {
              **"type": "calico-ipam",**
              "assign_ipv4": "true",
              "assign_ipv6": "false"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
          }
        },
        {
          "name": "sysctl-tuning",
          "type": "tuning",
          "sysctl": {
            "net.ipv4.tcp_keepalive_intvl": "1",
            "net.ipv4.tcp_keepalive_probes": "5",
            "net.ipv4.tcp_keepalive_time": "5"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }

Is it Multus issue, or Calico IPAM?

**Comment by tunicashashi** [comment]
Ohh sorry , What I mean to ask, is it SRIOV-Plugin -Multus, or Calico IPAM Issue?

**Comment by tunicashashi** [comment]
Ohh, thanks for noticing., it seems to be in default. I will create in namespace: sriov-data and let you know.

**Comment by tunicashashi** [comment]
@mukesh-dua ,  yes now I am able to start the pod but unable to set a default route.

I  tried to change the default route as below in the static configuration of IPAM network type in CRD file . 

"routes": [
                    { "dst": "0.0.0.0/0","gw": "10.127.53.65" },
                    { "dst": "10.127.53.0/24", "gw": "10.127.53.65" }
                ]

*and also through pod defination:*
apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  namespace : sriov-data
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{
      "name": "sriov-net1",
      "default-route": ["10.127.53.65"]
    }]'
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/pci_sriov_net_physnet134f0: '1'
      limits:
        intel.com/pci_sriov_net_physnet134f0: '1'

but pod shows:

controller-0:~/sriov_multus$  kubectl exec -it testpod1 -n sriov-data -- route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         169.254.1.1     0.0.0.0         UG    0      0        0 eth0
10.127.53.0     0.0.0.0         255.255.255.0   U     0      0        0 net1
169.254.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0

not even able to ping to the gateway I have configured. What am I doing wrong?

**Comment by tunicashashi** [comment]
the tcpdump on interface which has SR-IOV,
I got as below strange ARP request:

17:28:49.024530 LLDP, length 268: controller-0:ebca4f15-fa83-481a-9847-e8c90a251b42
17:28:56.762579 LLDP, length 263: Core-1
17:29:14.523811 ARP, Request who-has 10.127.53.65 tell 10.127.53.65, length 46

**Comment by killianmuldoon** [comment]
@tunicashashi did you ever get to the bottom of this issue?

**Comment by killianmuldoon** [comment]
Closed as stale
