### ISSUE TITLE
VFIO cannot be attached to a pod

### ISSUE THREAD

**Issue by peng-isi** [k8snetworkplumbingwg/sriov-network-device-plugin#270]
### What happened?
I configured the vfio-pci on one of IB VFs and the resource can be detected and advertised by the device plugin.  However, when I use Multus to attach 
the network interface to a pod, it fails.  I got the error message, 
"Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "701ace1833b3806c7575f238fa766a2bb8dc5df5c6c0f0d2f74785f63bc06987" network for pod "testpod1": networkPlugin cni failed to set up pod "testpod1_default" network: Multus: [default/testpod1]: error adding container to network "sriov-network": delegateAdd: error invoking DelegateAdd - "host-device": error in getting result from AddNetwork: failed to find host device: no net directory under pci device 0000:21:00.1,...". 

Do I misconfigure or miss  something here? I attached the configmap, NetworkAttachmentDefinition,  and the pod definition  in the following.

-------------------------------------------
the configmap is defined as

{
                "resourcePrefix": "mellanox.com",
                "resourceName": "vfio_ib_netdevice",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1004"],
                    "drivers": ["vfio-pci"]
                }
                }

-----------------------------
The NetworkAttachmentDefinition I used is attached as follows

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ib-sriov-network-vfio
  annotations:
          k8s.v1.cni.cncf.io/networks: mellanox.com/vfio_ib_netdevice
spec:
  config: '{
  "type": "host-device",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "pciBusID": "0000:21:00.1",
  "ipam": {
    "type": "static",
    "subnet": "12.12.12.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }]
  }
}'

---------------------
The pod is defined as

apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  annotations:
          k8s.v1.cni.cncf.io/networks: ib-sriov-network-vfio
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        mellanox.com/vfio_ib_netdevice: '1'
      limits:
        mellanox.com/vfio_ib_netdevice: '1'

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<Input Version Here>|
|SR-IOV CNI Plugin            |<Input Version Here>|
|Multus                       |<Input Version Here>|
|Kubernetes                   |<Input Version Here>| 
|OS                           |<Input Version Here>|

### Config Files
Config file locations may be config dependent.

**Comment by zshi-redhat** [comment]
@peng-isi any reason you're using host-device CNI for ib VF, instead of ib-sriov-cni ?
btw, when bind to vfio-pci, host-device cannot find the VF device as it will not appear as a kernel interface anymore. which caused the failure.

**Comment by peng-isi** [comment]
@zshi-redhat many thanks for the prompt reply.  

I checked the  previously reported issues and found your discussions on the vfio device passthrough. If my understanding is correct, we don't need sriov-cni to attach vfio device to a pod. That's the reason I updated the host-device cni and use it here. 

If I used "ib-sriov-cni", I got the following error message," rpc error: code = Unknown desc = [failed to set up sandbox container "b61ccc8712e07d176d08cde62d7bc6acf74e0f620a7113fe4d422287aa4c1e39" network for pod "testpod1": networkPlugin cni failed to set up pod "testpod1_default" network: Multus: [default/testpod1]: error adding container to network "sriov-network": delegateAdd: error invoking DelegateAdd - "ib-sriov": error in getting result from AddNetwork: failed to get device specific information. load config: vf pci addr is required, ... ". 

The final goal I want to achieve is to expose the IB VF to a VM running in a pod. I can expose the IB VF to the pod, but the VM running in the pod cannot access the IB VF because the VM is a user space program. That's the reason I want to bind the VF to vfio-pci in the first place so that a VM can access the IB interface through VFIO.  Is there any way to find the VF bind to vfio-pci?

**Comment by zshi-redhat** [comment]
> @zshi-redhat many thanks for the prompt reply.
> 
> I checked the previously reported issues and found your discussions on the vfio device passthrough. If my understanding is correct, we don't need sriov-cni to attach vfio device to a pod. That's the reason I updated the host-device cni and use it here.
> 
Correct, for vfio-pci device in VM, we don't need sriov-cni, as sriov devcie plugin shall handle the device passthough to contanier. we would not need host-device neither. you can leave the CNI part empty (not specify the net-attach-def in pod annotation), just request the vfio-pci resource in pod spec limits/requests.

> If I used "ib-sriov-cni", I got the following error message," rpc error: code = Unknown desc = [failed to set up sandbox container "b61ccc8712e07d176d08cde62d7bc6acf74e0f620a7113fe4d422287aa4c1e39" network for pod "testpod1": networkPlugin cni failed to set up pod "testpod1_default" network: Multus: [default/testpod1]: error adding container to network "sriov-network": delegateAdd: error invoking DelegateAdd - "ib-sriov": error in getting result from AddNetwork: failed to get device specific information. load config: vf pci addr is required, ... ".

Yes, CNI shall not be used in vfio-pci VM case.
> 
> The final goal I want to achieve is to expose the IB VF to a VM running in a pod. I can expose the IB VF to the pod, but the VM running in the pod cannot access the IB VF because the VM is a user space program. That's the reason I want to bind the VF to vfio-pci in the first place so that a VM can access the IB interface through VFIO. Is there any way to find the VF bind to vfio-pci?

Once you setup the pod correctly, the vfio-pci device will be seen under /dev/vfio/ directory inside container. the PCI address of that device can be observed in the environment variable inside contaier.

**Comment by peng-isi** [comment]
@zshi-redhat Many thanks for your help. Your suggestion works. If I use the pod spec limits/requests, the vfio can be exposed to the pod. However,  if I use the same way to expose the VFIO  to a VM in the VM configuration in KubeVirt, the vfio is visible to the pod hosting the VM, but not attached to the VM.  By any chance,  you may know the gaps between pod configuration  and VM configuration in Kubevirt. How to make the vfio the part of a VM?

**Comment by amorenoz** [comment]
Hi @peng-isi, In order to pass a SRIOV device to a VM, please see Kubevirt's doc:
https://kubevirt.io/user-guide/#/creation/interfaces-and-networks?id=how-to-expose-sr-iov-vfs-to-kubevirt

**Comment by peng-isi** [comment]
@amorenoz, many thanks for your help! I went through the docs you suggested and I am still confused. Right now, I already configured vfio-pci on one of the sriov VFs and the device plugin can detect and advertise the vfio on my node.  When I created a pod with spec limits/requests, the vfio resource can be added to the pod. 

I am trying to expose the vfio to a VM. If I use NetworkAttachmentDefinition to attach the  vfio device to a VM, I failed. based on @zshi-redhat's reply, "we don't need sriov-cni, as sriov devcie plugin shall handle the device passthough to contanier. we would not need host-device neither. you can leave the CNI part empty (not specify the net-attach-def in pod annotation), just request the vfio-pci resource in pod spec limits/requests." I tried to create a VM with spec limits/requests to expose the vfio. However, by doing so,  the vfio resource can be visible to the pod hosting the VM, but not to the VM. 

I am wondering if there is a way to map the device exposed by the "spec limits/requests" method to the  interface of a VM? or I miss something here?

**Comment by zshi-redhat** [comment]
I think kubevirt components would be responsible for attaching pod vfio device to libvirt VM by referencing it in the VM xml.
@SchSeba @phoracek do you have any idea what to check?

**Comment by moshe010** [comment]
regardless of what mention here I don't think kubevirt support IB VF see https://github.com/kubevirt/kubevirt/blob/46b64d68c920fe5466a7ee26121a66f256f91840/pkg/virt-controller/services/template.go#L1364-L1365 also there is not code to configure the VM node guid and port guid.

**Comment by peng-isi** [comment]
thank @moshe010 for your information. It is very helpful.

**Comment by martinkennelly** [comment]
Closing issue as it is not a problem with SRIOV DP.
