### ISSUE TITLE
Does this sriov project support Broadcom BCM57414 NIC ?

### ISSUE THREAD

**Issue by thanhlong9x** [k8snetworkplumbingwg/sriov-network-device-plugin#274]
Hi, I am using Broadcom BCM57414 NIC. But this NIC isn't indentified by sriov-device-plugin. So,I want to know if this NIC is supported or not.

Thank you

**Comment by zshi-redhat** [comment]
@thanhlong9x  I didn't test it myself, but I don't see how it cannot work for other types of devices.
If you hit any specific issue, please report it here so we can take a look.

**Comment by thisab** [comment]
Hi, 
We are trying SR-IOV with a BCM57416, but the instruction says:
`Make sure to update the 'config.json' entry in the configMap data to reflect your resource configuration for the device plugin. See [Configurations](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin#configurations) section for supported configuration parameters.`
But there is no Broadcom listed in the configuration parameters. 
How can we modify it to support this NIC?
