### ISSUE TITLE
Add additional extended Selectors to for networks in virtual deployments.

### ISSUE THREAD

**Issue by atyronesmith** [k8snetworkplumbingwg/sriov-network-device-plugin#277]
## What would you like to be added?
I would like to add the ability to select attached networks when running in a virtual environment.  
The two tags are:

- NetworkID -- A string representing the unique identifier for the attach SDN network.  For example, in OpenStack this would be a UUID.
- NetworkTag -- A string representing an identifying attribute/name that has been attached to the network.  For example, in OpenStack the SDN network to be attached has been tagged as _radio_uplink_a_.  

## What is the use case for this feature / enhancement?
When Kubernetes is run in a virtual environment (OpenStack, VMWare, etc...), additional SDN networks can be attached to the VM. In such environments as OpenStack, additional metadata is provided such that the UUID and tagging information
of a network is made available inside the VM running Kubernetes.  For example, a Kubernetes installer can provide
the UUID and/or additional tag information for the network that is being attached.   A proposed [PR](https://github.com/openshift/sriov-network-operator/pull/369) for the sriov-network-operator exposes this information via the sriovnetworknodestate CRD.   It would be desirable to allow this additional metadata be used to select the correct interface for the application.

**Comment by adrianchiris** [comment]
>I would like to add the ability to select attached networks when running in a virtual environment.>
>The two tags are:
>
>- NetworkID -- A string representing the unique identifier for the attach SDN network. For example, in OpenStack this would be a UUID.
>- NetworkTag -- A string representing an identifying attribute/name that has been attached to the network. For example, in > OpenStack the SDN network to be attached has been tagged as radio_uplink_a.

So there would need to be a mapping of some sort between PCI devices and tag(s).

A couple of questions here:
1. who exposes this information to the VM?
2. how is this information exposed ?

> a Kubernetes installer can provide
the UUID and/or additional tag information for the network that is being attached. A proposed PR for the sriov-network-operator exposes this information via the sriovnetworknodestate CRD. It would be desirable to allow this additional metadata be used to select the correct interface for the application.

Could the same kubernetes installer translate the platform metadata into a valid pool configuration via existing selectors ?

**Comment by atyronesmith** [comment]
There is a mapping between PCI addresses and tag(s).  The format of OpenStack data is shown [here](https://docs.openstack.org/nova/latest/user/metadata.html).  A snippet of an example is below...

`"hostname": "test.novalocal",
   "launch_index": 0,
   "meta": {
      "priority": "low",
      "role": "webserver"
   },
   "devices": [
       {
         "type": "nic",
         "bus": "pci",
         "address": "0000:00:02.0",
         "mac": "00:11:22:33:44:55",
         "tags": ["trusted"]
       },`

The mapping is in the meta_data.json file itself.  The tags are supplied when the VM is created in OpenStack by attaching an attribute to the -nic parameter i.e. for the above something like ...  nova boot .... -nic ...,tag="trusted".

The installer will include the user-defined tag.  An additional network_data.json file is also available which containers the following:

`{
    "links": [
        {
            "ethernet_mac_address": "fa:16:3e:9c:bf:3d",
            "id": "tapcd9f6d46-4a",
            "mtu": null,
            "type": "bridge",
            "vif_id": "cd9f6d46-4a3a-43ab-a466-994af9db96fc"
        }
    ],
    "networks": [
        {
            "id": "network0",
            "link": "tapcd9f6d46-4a",
            "network_id": "99e88329-f20d-4741-9593-25bf07847b16",
            "type": "ipv4_dhcp"
        }
    ],
    "services": [
        {
            "address": "8.8.8.8",
            "type": "dns"
        }
    ]
`
The network_data.json file provides the UUID of the underlying network.

> Could the same kubernetes installer translate the platform metadata into a valid pool configuration via existing selectors ?

Excellent question...  Unfortunately, the target PCI address is not know by the installer before invoking the server create command.  However, the sriov-network-operator does know the target pci address.  The operator could do a match and fill in the rootDevice field with the pci address of the matching NetworkID and/or NetworkTag.   However, while the matching is done inside the network-config-daemon of the operator and is specific to a particular node, there is only one configFile for the sriov-network-device-plugin.  The pci address inside the VM would need to be guaranteed to be the same on all VMs.  This behaviour is not specified by the OpenStack API.  One solution at the sriov-network-operator level would be separate config files for each sriov-network-device-plugin.

**Comment by zshi-redhat** [comment]
one question, how would we expect device plugin to parse the metadata file. does it need to understand the openstack metadata file structure?

**Comment by moshe010** [comment]
regarding "sriov-network-operator level would be separate config files" maybe we should update the sriov-device-plugin also to extend the resources from local file on the node. So the configmap is globe across cluster but you can add additional file to extend it per node. 
for example: 

{
    "resourceList": [{
            "resourceName": "intel_sriov_netdevice",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["154c", "10ed"],
                "drivers": ["i40evf", "ixgbevf"]
            }
        },
   ], 
   "extra_resources": "extra_resources.json"
}
The SR-IOV operator can create it extra_resource.json per node. The SR-IOV device plugin  merged the resourceList in the configMap with the extra_resources.json file to one resourceList. 
each node will have it own extra_resources.json per the VM.

**Comment by atyronesmith** [comment]
> one question, how would we expect device plugin to parse the metadata file. does it need to understand the openstack metadata file structure?

The device plugin would not need to parse the metadata file if the NetworkID and NetworkTag fields are added.  A higher level process (i.e. the sriov-network-operator/sriov-network-config-daemon) would do the parsing of the metadata information (the parsing is in the current PR) and place it in the configMap for the device-plugin.  NetworkID, NetworkTag would then be used as another selector in the device-plugin logic.  The NetworkID and NetworkTag are globally consistent and since the matching is being done by the device plugin on each node, there would not need to be specific to the node.

**Comment by atyronesmith** [comment]
I had made a mistake in thinking that the device plugin would not need to parse metadata.  Need to discuss the node-specific configuration method...

**Comment by atyronesmith** [comment]
[PR 279](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/279)  Should eliminate the need to additional Selectors.  With individual config files, the correct device can be selected using the PciAddress for the specific node inside the SR-IOV operator.

**Comment by atyronesmith** [comment]
Closing this for now.
