### ISSUE TITLE
Enable the use of vfio-noiommu when kubernetes is run in a virtual environment.

### ISSUE THREAD

**Issue by atyronesmith** [k8snetworkplumbingwg/sriov-network-device-plugin#278]
## What would you like to be added?
The ability to detect the presence of /dev/vfio/noiommu-N devices and mount the noiommu-N device inside the container as a normal vfio device, i.e. /dev/vfio/N
## What is the use case for this feature / enhancement?
Some virtual environment, for example OpenStack, do not yet support a virtualized iommu implementation.  This enhancement would allow the use of the noiommu option of the vfio driver until such support is added.

**Comment by adrianchiris** [comment]
PR #272 addresses this enhancement and was merged. @atyronesmith  is there additional work that is planned for this enhancement ?

**Comment by atyronesmith** [comment]
> PR #272 addresses this enhancement and was merged. @atyronesmith is there additional work that is planned for this enhancement ?

Hi, No there is not.  Let me close the issue.

**Comment by atyronesmith** [comment]
Feature complete
