### ISSUE TITLE
Resource names containing hyphens will fail

### ISSUE THREAD

**Issue by martinkennelly** [k8snetworkplumbingwg/sriov-network-device-plugin#288]
### What happened?
Including a hyphen in a resource name causes SRIOV DP failure at startup.

### What did you expect to happen?
Hyphens are ok in resource names

### What are the minimal steps needed to reproduce the bug?
Include hyphen in resource name
### Anything else we need to know?
NA
### Component Versions
All versions

I checked K8 object API naming convention and hyphens are ok. I checked  Is there a reason why we do not allow it in SRIOV DP?

Regex of resource name:
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/4563418370e11a92c0c1349b65d32e79a3449fc6/pkg/utils/utils.go#L257

I tried looking for K8 object naming convention: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

Is this behavior ok with the community?

**Comment by zshi-redhat** [comment]
I forgot why we disable that, but there was a reason. @ahalim-intel do you remember?

**Comment by adrianchiris** [comment]
As i see, the resource name is injected as environment variable into pod in the format `<PCIDEVICE>_<ResourceNameUpperCase>`

e.g:
`PCIDEVICE_MY_PCI_RESOURCE=0000:06:02.7`

environment variables cannot have hyphens so they would need to be translated to another char (not underscore...)

**Comment by martinkennelly** [comment]
@adrianchiris Thank you. 
I will add short PR to add to docs.
