### ISSUE TITLE
.PHONY targets could all be defined in one line

### ISSUE THREAD

**Issue by mrymsza** [k8snetworkplumbingwg/sriov-network-device-plugin#294]
## What issue would you like to bring attention to?
.PHONY targets are not defined in one line at the top.

## What is the impact of this issue?
Defining .PHONY targets all over the file makes the Makefile not easy to read.

## Do you have a proposed response or remediation for the issue?
It's probably better practice to keep all .PHONY commands together at the top.

**Comment by martinkennelly** [comment]
Closing issue. Will not implement.
