### ISSUE TITLE
sriov-device-plugin did not find the vf on the host device

### ISSUE THREAD

**Issue by aliasmee** [k8snetworkplumbingwg/sriov-network-device-plugin#310]
### What happened?

sriov-device-plugin did not find the vf on the host device。Thanks！

```bash
I0106 13:12:42.114231       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:01:00.0 02              Intel Corporation       I350 Gigabit Network Connection         
I0106 13:12:42.114390       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:01:00.1 02              Intel Corporation       I350 Gigabit Network Connection         
I0106 13:12:42.114473       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:05:00.0 02              Intel Corporation       Ethernet Controller X710 for 10GbE SFP+ 
I0106 13:12:42.115312       1 netDeviceProvider.go:116] excluding interface eth5:  default route found: {Ifindex: 7 Dst: <nil> Src: <nil> Gw: 10.46.155.33 Flags: [] Table: 254}
I0106 13:12:42.115448       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:05:00.1 02              Intel Corporation       Ethernet Controller X710 for 10GbE SFP+ 
I0106 13:12:42.115924       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.0 02              Mellanox Technolo...    MT27800 Family [ConnectX-5]             
I0106 13:12:42.118312       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.1 02              Mellanox Technolo...    MT27800 Family [ConnectX-5]             
I0106 13:12:42.118839       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.2 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.119830       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.3 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.120348       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.4 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.120801       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.5 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.121240       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.6 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.121690       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.7 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.122124       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:01.0 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.122562       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:01.1 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.123000       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:4c:00.0 02              Mellanox Technolo...    MT27800 Family [ConnectX-5]             
I0106 13:12:42.123506       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:4c:00.1 02              Mellanox Technolo...    MT27800 Family [ConnectX-5]             
I0106 13:12:42.123977       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:7c:00.0 02              Intel Corporation       I350 Gigabit Network Connection         
I0106 13:12:42.124069       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:7c:00.1 02              Intel Corporation       I350 Gigabit Network Connection         
I0106 13:12:42.124157       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:88:00.0 02              Mellanox Technolo...    MT27700 Family [ConnectX-4]             
I0106 13:12:42.124678       1 main.go:66] Initializing resource servers
I0106 13:12:42.124694       1 manager.go:112] number of config: 1
I0106 13:12:42.124704       1 manager.go:115] 
I0106 13:12:42.124714       1 manager.go:116] Creating new ResourcePool: mlnx_sriov_rdma
I0106 13:12:42.124722       1 manager.go:117] DeviceType: netDevice
E0106 13:12:42.124764       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:01:00.0 readlink /sys/bus/pci/devices/0000:01:00.0/driver: no such file or directory"
E0106 13:12:42.125152       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:01:00.1 readlink /sys/bus/pci/devices/0000:01:00.1/driver: no such file or directory"
W0106 13:12:42.125218       1 pciNetDevice.go:55] RDMA resources for 0000:05:00.1 not found. Are RDMA modules loaded?
E0106 13:12:42.144174       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:7c:00.0 readlink /sys/bus/pci/devices/0000:7c:00.0/driver: no such file or directory"
E0106 13:12:42.144204       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:7c:00.1 readlink /sys/bus/pci/devices/0000:7c:00.1/driver: no such file or directory"
I0106 13:12:42.145356       1 factory.go:108] device added: [pciAddr: 0000:17:00.1, vendor: 15b3, device: 1017, driver: mlx5_core]
I0106 13:12:42.145369       1 factory.go:108] device added: [pciAddr: 0000:4c:00.0, vendor: 15b3, device: 1017, driver: mlx5_core]
I0106 13:12:42.145376       1 factory.go:108] device added: [pciAddr: 0000:4c:00.1, vendor: 15b3, device: 1017, driver: mlx5_core]
I0106 13:12:42.145404       1 manager.go:145] New resource server is created for mlnx_sriov_rdma ResourcePool
I0106 13:12:42.145415       1 main.go:72] Starting all servers...
I0106 13:12:42.145708       1 server.go:196] starting mlnx_sriov_rdma device plugin endpoint at: intel.com_mlnx_sriov_rdma.sock
I0106 13:12:42.146418       1 server.go:222] mlnx_sriov_rdma device plugin endpoint started serving
I0106 13:12:42.146452       1 main.go:77] All servers started.
I0106 13:12:42.146461       1 main.go:78] Listening for term signals
I0106 13:12:42.476764       1 server.go:106] Plugin: intel.com_mlnx_sriov_rdma.sock gets registered successfully at Kubelet
I0106 13:12:42.476881       1 server.go:131] ListAndWatch(mlnx_sriov_rdma) invoked
I0106 13:12:42.476911       1 server.go:139] ListAndWatch(mlnx_sriov_rdma): send devices &ListAndWatchResponse{Devices:[]*Device{&Device{ID:0000:17:00.1,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:4c:00.0,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:4c:00.1,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},},}
I0107 02:29:36.087053       1 server.go:115] Allocate() called with &AllocateRequest{ContainerRequests:[]*ContainerAllocateRequest{&ContainerAllocateRequest{DevicesIDs:[0000:17:00.1],},},}
I0107 02:29:36.087232       1 netResourcePool.go:50] GetDeviceSpecs(): for devices: [0000:17:00.1]
I0107 02:29:36.087304       1 pool_stub.go:97] GetEnvs(): for devices: [0000:17:00.1]
I0107 02:29:36.087319       1 pool_stub.go:113] GetMounts(): for devices: [0000:17:00.1]


```

### What did you expect to happen?

Add vf to resourcePoll.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |v3.2|
|Multus                       |v3.6|
|Kubernetes                   |1.16| 
|OS                           |centos7.5|

### Config Files
Config file locations may be config dependent.

##### CNI config (Try '/etc/cni/net.d/')

```bash
 cat /etc/cni/net.d/00-multus.conf 
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "cbr0", "cniVersion": "0.3.1", "plugins": [ { "type": "flannel", "delegate": { "hairpinMode": true, "isDefaultGateway": true } }, { "type": "portmap", "capabilities": { "portMappings": true } } ] } ] }

```

```BASH
# cat /etc/cni/net.d/10-flannel.conflist 
{
  "name": "cbr0",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}

```

##### Kubernetes deployment type ( Bare Metal, Kubeadm etc.)
kubeadm + Bare Metal

##### SR-IOV Network Custom Resource Definition

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.217.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.56.217.1"
  }
}'

##### SR-IOV Network Device Plugin Logs (use `kubectl logs $PODNAME`)
I0106 13:12:42.038069       1 factory.go:168] net device selector for resource mlnx_sriov_rdma is &{DeviceSelectors:{Vendors:[15b3] Devices:[1017] Drivers:[mlx5_core] PciAddresses:[]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:true NeedVhostNet:false}
I0106 13:12:42.038103       1 manager.go:106] unmarshalled ResourceList: [{ResourcePrefix: ResourceName:mlnx_sriov_rdma DeviceType:netDevice Selectors:0xc000214f20 SelectorObj:0xc000318820}]
I0106 13:12:42.038161       1 manager.go:193] validating resource name "intel.com/mlnx_sriov_rdma"
I0106 13:12:42.038173       1 main.go:60] Discovering host devices
I0106 13:12:42.114231       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:01:00.0 02              Intel Corporation       I350 Gigabit Network Connection         
I0106 13:12:42.114390       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:01:00.1 02              Intel Corporation       I350 Gigabit Network Connection         
I0106 13:12:42.114473       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:05:00.0 02              Intel Corporation       Ethernet Controller X710 for 10GbE SFP+ 
I0106 13:12:42.115312       1 netDeviceProvider.go:116] excluding interface eth5:  default route found: {Ifindex: 7 Dst: <nil> Src: <nil> Gw: 10.46.155.33 Flags: [] Table: 254}
I0106 13:12:42.115448       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:05:00.1 02              Intel Corporation       Ethernet Controller X710 for 10GbE SFP+ 
I0106 13:12:42.115924       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.0 02              Mellanox Technolo...    MT27800 Family [ConnectX-5]             
I0106 13:12:42.118312       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.1 02              Mellanox Technolo...    MT27800 Family [ConnectX-5]             
I0106 13:12:42.118839       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.2 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.119830       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.3 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.120348       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.4 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.120801       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.5 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.121240       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.6 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.121690       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:00.7 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.122124       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:01.0 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.122562       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:17:01.1 02              Mellanox Technolo...    MT27800 Family [ConnectX-5 Virtual Fu...
I0106 13:12:42.123000       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:4c:00.0 02              Mellanox Technolo...    MT27800 Family [ConnectX-5]             
I0106 13:12:42.123506       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:4c:00.1 02              Mellanox Technolo...    MT27800 Family [ConnectX-5]             
I0106 13:12:42.123977       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:7c:00.0 02              Intel Corporation       I350 Gigabit Network Connection         
I0106 13:12:42.124069       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:7c:00.1 02              Intel Corporation       I350 Gigabit Network Connection         
I0106 13:12:42.124157       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:88:00.0 02              Mellanox Technolo...    MT27700 Family [ConnectX-4]             
I0106 13:12:42.124678       1 main.go:66] Initializing resource servers
I0106 13:12:42.124694       1 manager.go:112] number of config: 1
I0106 13:12:42.124704       1 manager.go:115] 
I0106 13:12:42.124714       1 manager.go:116] Creating new ResourcePool: mlnx_sriov_rdma
I0106 13:12:42.124722       1 manager.go:117] DeviceType: netDevice
E0106 13:12:42.124764       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:01:00.0 readlink /sys/bus/pci/devices/0000:01:00.0/driver: no such file or directory"
E0106 13:12:42.125152       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:01:00.1 readlink /sys/bus/pci/devices/0000:01:00.1/driver: no such file or directory"
W0106 13:12:42.125218       1 pciNetDevice.go:55] RDMA resources for 0000:05:00.1 not found. Are RDMA modules loaded?
E0106 13:12:42.144174       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:7c:00.0 readlink /sys/bus/pci/devices/0000:7c:00.0/driver: no such file or directory"
E0106 13:12:42.144204       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:7c:00.1 readlink /sys/bus/pci/devices/0000:7c:00.1/driver: no such file or directory"
I0106 13:12:42.145356       1 factory.go:108] device added: [pciAddr: 0000:17:00.1, vendor: 15b3, device: 1017, driver: mlx5_core]
I0106 13:12:42.145369       1 factory.go:108] device added: [pciAddr: 0000:4c:00.0, vendor: 15b3, device: 1017, driver: mlx5_core]
I0106 13:12:42.145376       1 factory.go:108] device added: [pciAddr: 0000:4c:00.1, vendor: 15b3, device: 1017, driver: mlx5_core]
I0106 13:12:42.145404       1 manager.go:145] New resource server is created for mlnx_sriov_rdma ResourcePool
I0106 13:12:42.145415       1 main.go:72] Starting all servers...
I0106 13:12:42.145708       1 server.go:196] starting mlnx_sriov_rdma device plugin endpoint at: intel.com_mlnx_sriov_rdma.sock
I0106 13:12:42.146418       1 server.go:222] mlnx_sriov_rdma device plugin endpoint started serving
I0106 13:12:42.146452       1 main.go:77] All servers started.
I0106 13:12:42.146461       1 main.go:78] Listening for term signals
I0106 13:12:42.476764       1 server.go:106] Plugin: intel.com_mlnx_sriov_rdma.sock gets registered successfully at Kubelet
I0106 13:12:42.476881       1 server.go:131] ListAndWatch(mlnx_sriov_rdma) invoked
I0106 13:12:42.476911       1 server.go:139] ListAndWatch(mlnx_sriov_rdma): send devices &ListAndWatchResponse{Devices:[]*Device{&Device{ID:0000:17:00.1,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:4c:00.0,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:4c:00.1,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},},}
I0107 02:29:36.087053       1 server.go:115] Allocate() called with &AllocateRequest{ContainerRequests:[]*ContainerAllocateRequest{&ContainerAllocateRequest{DevicesIDs:[0000:17:00.1],},},}
I0107 02:29:36.087232       1 netResourcePool.go:50] GetDeviceSpecs(): for devices: [0000:17:00.1]
I0107 02:29:36.087304       1 pool_stub.go:97] GetEnvs(): for devices: [0000:17:00.1]
I0107 02:29:36.087319       1 pool_stub.go:113] GetMounts(): for devices: [0000:17:00.1]
I0107 02:29:36.087331       1 server.go:124] AllocateResponse send: &AllocateResponse{ContainerResponses:[]*ContainerAllocateResponse{&ContainerAllocateResponse{Envs:map[string]string{PCIDEVICE_INTEL_COM_MLNX_SRIOV_RDMA: 0000:17:00.1,},Mounts:[]*Mount{},Devices:[]*DeviceSpec{&DeviceSpec{ContainerPath:/dev/infiniband/issm1,HostPath:/dev/infiniband/issm1,Permissions:rwm,},&DeviceSpec{ContainerPath:/dev/infiniband/umad1,HostPath:/dev/infiniband/umad1,Permissions:rwm,},&DeviceSpec{ContainerPath:/dev/infiniband/uverbs1,HostPath:/dev/infiniband/uverbs1,Permissions:rwm,},&DeviceSpec{ContainerPath:/dev/infiniband/rdma_cm,HostPath:/dev/infiniband/rdma_cm,Permissions:rwm,},},Annotations:map[string]string{},}

##### Multus logs (If enabled. Try '/var/log/multus.log' )
2021-01-06T11:12:41+0000 Generating Multus configuration file using files in /host/etc/cni/net.d...
2021-01-06T11:12:41+0000 Using /host/etc/cni/net.d/10-flannel.conflist as a source to generate the Multus configuration
2021-01-06T11:12:41+0000 Config file created @ /host/etc/cni/net.d/00-multus.conf
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "cbr0", "cniVersion": "0.3.1", "plugins": [ { "type": "flannel", "delegate": { "hairpinMode": true, "isDefaultGateway": true } }, { "type": "portmap", "capabilities": { "portMappings": true } } ] } ] }
2021-01-06T11:12:41+0000 Entering sleep (success)...

**Comment by zshi-redhat** [comment]
@aliasmee looks like you are using PF device ID for `devices` selector in device plugin configmap , could you try change it to VF device ID (1018)?

**Comment by aliasmee** [comment]
> @aliasmee looks like you are using PF device ID for `devices` selector in device plugin configmap , could you try change it to VF device ID (1018)?

@zshi-redhat thanks，you are right。The vf device has been added to the pool when set devices id to ["1018"]。（I ignored that there are multiple devices of different types on the host）。

感谢。

**Comment by aliasmee** [comment]
@zshi-redhat However, the pod in pod-tc1.yaml still fails to start and is being ContainerCreating.  Do you have a good idea?  thanks!

ERROR LOG：
```BASH
error adding container to network "sriov-network": SRIOV-CNI failed to load netconf: LoadConf(): VF pci addr is required, failed to clean up sandbox container 
```


```bash
# kubectl describe po testpod1
  ----     ------                  ----               ----                                     -------
  Normal   Scheduled               33s                default-scheduler                        Successfully assigned default/testpod1 to gpu1.xx.cn
  Normal   AddedInterface          32s                multus                                   Add eth0 [10.244.1.61/24]
  Warning  FailedCreatePodSandBox  31s                kubelet, gpu1.xx.cn  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "87d7b92309c64f17c11cada71d47585bc68d0f2b91aae4ff740cd0a51f28a40e" network for pod "testpod1": networkPlugin cni failed to set up pod "testpod1_default" network: [default/testpod1:sriov-network]: error adding container to network "sriov-network": SRIOV-CNI failed to load netconf: LoadConf(): VF pci addr is required, failed to clean up sandbox container "87d7b92309c64f17c11cada71d47585bc68d0f2b91aae4ff740cd0a51f28a40e" network for pod "testpod1": networkPlugin cni failed to teardown pod "testpod1_default" network: delegateDel: error invoking DelegateDel - "sriov": error in getting result from DelNetwork: error reading cached NetConf in /var/lib/cni/sriov with name 87d7b92309c64f17c11cada71d47585bc68d0f2b91aae4ff740cd0a51f28a40e-net1]
  Normal   AddedInterface          30s                multus                                   Add eth0 [10.244.1.62/24]
  Warning  FailedCreatePodSandBox  30s                kubelet, gpu1.xx.cn  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "9d1452dac55e93bfdf4e0b35669fc662109f61e25e513c1c6ad3fb80a6982b86" network for pod "testpod1": networkPlugin cni failed to set up pod "testpod1_default" network: [default/testpod1:sriov-network]: error adding container to network "sriov-network": SRIOV-CNI failed to load netconf: LoadConf(): VF pci addr is required, failed to clean up sandbox container "9d1452dac55e93bfdf4e0b35669fc662109f61e25e513c1c6ad3fb80a6982b86" network for pod "testpod1": networkPlugin cni failed to teardown pod "testpod1_default" network: delegateDel: error invoking DelegateDel - "sriov": error in getting result from DelNetwork: error reading cached NetConf in /var/lib/cni/sriov with name 9d1452dac55e93bfdf4e0b35669fc662109f61e25e513c1c6ad3fb80a6982b86-net1]
  Normal   AddedInterface          28s                multus                                   Add eth0 [10.244.1.63/24]

```

**Comment by aliasmee** [comment]
I have found the reason. Error caused by inconsistent resourceName defined in file deployments/configMap.yaml and file deployments/sriov-crd.yaml

Thanks。

```BASH
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/mlnx_sriov_rdma

```

SRIOVDP-CONFIG file:
```BASH
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "mlnx_sriov_rdma",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1018"],
                    "drivers": ["mlx5_core"],
                    "isRdma": true
                }
            }
        ]
    }

```

**Comment by zshi-redhat** [comment]
> I have found the reason. Error caused by inconsistent resourceName defined in file deployments/configMap.yaml and file deployments/sriov-crd.yaml
> 

Cool, multus parses the resource name from net-attach-def and pass the device ID to sriov-cni, you got it right.
Closing the issue.
