### ISSUE TITLE
sriov-network-device-plugin is unable to load Mellanox DPDK device (readlink failure)

### ISSUE THREAD

**Issue by praveingk** [k8snetworkplumbingwg/sriov-network-device-plugin#314]
## What issue would you like to bring attention to?

SRIOV-network-device-plugin fails to load the device selector mentioned in the configuration :
**The logs of the plugin** 

$ kubectl -n kube-system logs kube-sriov-device-plugin-amd64-c5ssv 
I0118 11:43:42.739952       1 manager.go:52] Using Kubelet Plugin Registry Mode
I0118 11:43:42.740270       1 main.go:44] resource manager reading configs
I0118 11:43:42.740362       1 manager.go:86] raw ResourceList: {
    "resourceList": [{
            "resourceName": "mlnx_sriov_dpdk",
            "resourceprefix": "mellanox.com",
            "selectors": {
                "vendors": ["15b3"],
                "devices": ["1019"],
                "drivers": ["vfio-pci", "igb_uio"],
                "pciAddresses": ["0000:1f:00.1"],
                "pfNames": ["ens3f1"],
                "rootDevices": ["000:1f:00.1"]
            }
        }
    ]
}
I0118 11:43:42.740421       1 factory.go:168] net device selector for resource mlnx_sriov_dpdk is &{DeviceSelectors:{Vendors:[15b3] Devices:[1019] Drivers:[vfio-pci igb_uio] PciAddresses:[0000:1f:00.1]} PfNames:[ens3f1] RootDevices:[000:1f:00.1] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I0118 11:43:42.740439       1 manager.go:106] unmarshalled ResourceList: [{ResourcePrefix:mellanox.com ResourceName:mlnx_sriov_dpdk DeviceType:netDevice Selectors:0xc000260f20 SelectorObj:0xc000358820}]
I0118 11:43:42.740468       1 manager.go:193] validating resource name "mellanox.com/mlnx_sriov_dpdk"
I0118 11:43:42.740476       1 main.go:60] Discovering host devices
I0118 11:43:42.792864       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:0b:00.0	02          	Broadcom Inc. and...	NetXtreme II BCM5709 Gigabit Ethernet   
I0118 11:43:42.793154       1 netDeviceProvider.go:116] excluding interface eno1:  default route found: {Ifindex: 2 Dst: <nil> Src: <nil> Gw: 9.2.130.2 Flags: [] Table: 254}
I0118 11:43:42.793213       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:0b:00.1	02          	Broadcom Inc. and...	NetXtreme II BCM5709 Gigabit Ethernet   
I0118 11:43:42.793257       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:1f:00.0	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex]          
I0118 11:43:42.793317       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:1f:00.1	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex]          
I0118 11:43:42.793381       1 main.go:66] Initializing resource servers
I0118 11:43:42.793395       1 manager.go:112] number of config: 1
I0118 11:43:42.793399       1 manager.go:115] 
I0118 11:43:42.793403       1 manager.go:116] Creating new ResourcePool: mlnx_sriov_dpdk
I0118 11:43:42.793408       1 manager.go:117] DeviceType: netDevice
**E0118 11:43:42.793432       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:0b:00.1 readlink /sys/bus/pci/devices/0000:0b:00.1/driver: no such file or directory"
E0118 11:43:42.793757       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:1f:00.0 readlink /sys/bus/pci/devices/0000:1f:00.0/driver: no such file or directory"
E0118 11:43:42.793777       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:1f:00.1 readlink /sys/bus/pci/devices/0000:1f:00.1/driver: no such file or directory"**
I0118 11:43:42.793794       1 manager.go:130] no devices in device pool, skipping creating resource server for mlnx_sriov_dpdk
I0118 11:43:42.793802       1 main.go:72] Starting all servers...
I0118 11:43:42.793807       1 main.go:77] All servers started.
I0118 11:43:42.793812       1 main.go:78] Listening for term signals

Separately, when I try to perform the same command, it works fine :

$  readlink /sys/bus/pci/devices/0000\:1f\:00.1/driver
../../../../bus/pci/drivers/igb_uio

## What is the impact of this issue?
The dpdk device is not allocated to the node for SRIOV.

## Do you have a proposed response or remediation for the issue?

SRIOV CRD is defined as follows:

$ cat sriov_yamls/sriov_cni.yaml 
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox.com/mlnx_sriov_dpdk
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-dpdk",
  "type": "sriov",
  "vlan": 1000
}'

**Comment by moshe010** [comment]
Please see docs dpdk [1] on how to configure Mellanox with dpdk


[1] https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/master/docs/dpdk/mlnx-dpdk/configMap.yaml

**Comment by praveingk** [comment]
Thanks, I followed the config provided, and there is some progress where the driver is detected. However, the resource for the mellanox device is still not created. Please find the logs below :

$ kubectl -n kube-system logs kube-sriov-device-plugin-amd64-jgdcj
I0119 04:29:05.997868       1 manager.go:52] Using Kubelet Plugin Registry Mode
I0119 04:29:05.998276       1 main.go:44] resource manager reading configs
I0119 04:29:05.998423       1 manager.go:86] raw ResourceList: {
    "resourceList": [{
            "resourcePrefix": "mellanox.com",
            "resourceName": "mlnx_connectx5",
            "selectors": {
                "vendors": ["15b3"],
                "devices": ["1019"],
                "drivers": ["mlx5_core"]
            }
        }
    ]
}
I0119 04:29:05.998514       1 factory.go:168] net device selector for resource mlnx_connectx5 is &{DeviceSelectors:{Vendors:[15b3] Devices:[1019] Drivers:[mlx5_core] PciAddresses:[]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I0119 04:29:05.998545       1 manager.go:106] unmarshalled ResourceList: [{ResourcePrefix:mellanox.com ResourceName:mlnx_connectx5 DeviceType:netDevice Selectors:0xc0001d0f20 SelectorObj:0xc0002d6a90}]
I0119 04:29:05.998604       1 manager.go:193] validating resource name "mellanox.com/mlnx_connectx5"
I0119 04:29:05.998618       1 main.go:60] Discovering host devices
I0119 04:29:06.055780       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:0b:00.0	02          	Broadcom Inc. and...	NetXtreme II BCM5709 Gigabit Ethernet   
I0119 04:29:06.056163       1 netDeviceProvider.go:116] excluding interface eno1:  default route found: {Ifindex: 2 Dst: <nil> Src: <nil> Gw: 9.2.130.1 Flags: [onlink] Table: 254}
I0119 04:29:06.056233       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:0b:00.1	02          	Broadcom Inc. and...	NetXtreme II BCM5709 Gigabit Ethernet   
I0119 04:29:06.056409       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:1f:00.0	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex]          
I0119 04:29:06.057043       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:1f:00.1	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex]          
I0119 04:29:06.057548       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:1f:00.2	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0119 04:29:06.057721       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:1f:00.3	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0119 04:29:06.057886       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:1f:01.2	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0119 04:29:06.058074       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:1f:01.3	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0119 04:29:06.058243       1 main.go:66] Initializing resource servers
I0119 04:29:06.058258       1 manager.go:112] number of config: 1
I0119 04:29:06.058263       1 manager.go:115] 
I0119 04:29:06.058268       1 manager.go:116] Creating new ResourcePool: mlnx_connectx5
I0119 04:29:06.058272       1 manager.go:117] DeviceType: netDevice
**I0119 04:29:06.060596       1 manager.go:130] no devices in device pool, skipping creating resource server for mlnx_connectx5**
I0119 04:29:06.060610       1 main.go:72] Starting all servers...
I0119 04:29:06.060615       1 main.go:77] All servers started.
I0119 04:29:06.060621       1 main.go:78] Listening for term signals


$ cat sriov_yamls/sriov_crd_connectx5.yaml 
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-dpdk-mlnx-connectx5
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox.com/mlnx_connectx5
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "sriov",
    "name": "sriov-mlnx-connectx5",
    "ipam": {
      "type": "host-local",
      "subnet": "10.56.217.0/24",
      "routes": [{
        "dst": "0.0.0.0/0"
      }],
      "gateway": "10.56.217.1"
    }
}'

**Comment by praveingk** [comment]
After changing the device selector's device id to "101a", the VF, the device got selected correctly. Please note that the config I have used is :

    "resourceList": [{
            "resourcePrefix": "mellanox.com",
            "resourceName": "mlnx_connectx5",
            "selectors": {
                "vendors": ["15b3"],
                "devices": ["101a"],
                "drivers": ["mlx5_core"]
            }
        }
    ]
}

for the device :

1f:00.0 Ethernet controller [0200]: Mellanox Technologies MT28800 Family [ConnectX-5 Ex] [15b3:1019]
1f:00.1 Ethernet controller [0200]: Mellanox Technologies MT28800 Family [ConnectX-5 Ex] [15b3:1019]
1f:00.2 Ethernet controller [0200]: Mellanox Technologies MT28800 Family [ConnectX-5 Ex Virtual Function] [15b3:101a]
1f:00.3 Ethernet controller [0200]: Mellanox Technologies MT28800 Family [ConnectX-5 Ex Virtual Function] [15b3:101a]
1f:01.2 Ethernet controller [0200]: Mellanox Technologies MT28800 Family [ConnectX-5 Ex Virtual Function] [15b3:101a]
1f:01.3 Ethernet controller [0200]: Mellanox Technologies MT28800 Family [ConnectX-5 Ex Virtual Function] [15b3:101a]

**Comment by moshe010** [comment]
You also need isRDMA flag to be true  for dpdk application to work

**Comment by praveingk** [comment]
When I set isRdma flag as true , I get the below error :

$ kubectl -n kube-system logs kube-sriov-device-plugin-amd64-gfz4f
I0119 05:38:13.747787       1 manager.go:52] Using Kubelet Plugin Registry Mode
I0119 05:38:13.748146       1 main.go:44] resource manager reading configs
I0119 05:38:13.748234       1 manager.go:86] raw ResourceList: {
    "resourceList": [{
            "resourcePrefix": "mellanox.com",
            "resourceName": "mlnx_connectx5",
            "selectors": {
                "vendors": ["15b3"],
                "devices": ["101a"],
                "drivers": ["mlx5_core"],
                "isRdma": true
            }
        }
    ]
}
I0119 05:38:13.748288       1 factory.go:168] net device selector for resource mlnx_connectx5 is &{DeviceSelectors:{Vendors:[15b3] Devices:[101a] Drivers:[mlx5_core] PciAddresses:[]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:true NeedVhostNet:false}
I0119 05:38:13.748307       1 manager.go:106] unmarshalled ResourceList: [{ResourcePrefix:mellanox.com ResourceName:mlnx_connectx5 DeviceType:netDevice Selectors:0xc0001e2f20 SelectorObj:0xc0002e6b60}]
I0119 05:38:13.748343       1 manager.go:193] validating resource name "mellanox.com/mlnx_connectx5"
I0119 05:38:13.748354       1 main.go:60] Discovering host devices
I0119 05:38:13.800944       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:0b:00.0	02          	Broadcom Inc. and...	NetXtreme II BCM5709 Gigabit Ethernet   
I0119 05:38:13.801264       1 netDeviceProvider.go:116] excluding interface eno1:  default route found: {Ifindex: 2 Dst: <nil> Src: <nil> Gw: 9.2.130.2 Flags: [] Table: 254}
I0119 05:38:13.801330       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:0b:00.1	02          	Broadcom Inc. and...	NetXtreme II BCM5709 Gigabit Ethernet   
I0119 05:38:13.801366       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:1f:00.0	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex]          
I0119 05:38:13.801416       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:1f:00.1	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex]          
I0119 05:38:13.801485       1 main.go:66] Initializing resource servers
I0119 05:38:13.801497       1 manager.go:112] number of config: 1
I0119 05:38:13.801504       1 manager.go:115] 
I0119 05:38:13.801510       1 manager.go:116] Creating new ResourcePool: mlnx_connectx5
I0119 05:38:13.801519       1 manager.go:117] DeviceType: netDevice
E0119 05:38:13.801540       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:0b:00.1 readlink /sys/bus/pci/devices/0000:0b:00.1/driver: no such file or directory"
E0119 05:38:13.801880       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:1f:00.0 readlink /sys/bus/pci/devices/0000:1f:00.0/driver: no such file or directory"
E0119 05:38:13.801901       1 netDeviceProvider.go:52] netdevice GetDevices(): error creating new device: "error getting driver info for device 0000:1f:00.1 readlink /sys/bus/pci/devices/0000:1f:00.1/driver: no such file or directory"
I0119 05:38:13.801914       1 manager.go:130] no devices in device pool, skipping creating resource server for mlnx_connectx5
I0119 05:38:13.801920       1 main.go:72] Starting all servers...
I0119 05:38:13.801925       1 main.go:77] All servers started.
I0119 05:38:13.801931       1 main.go:78] Listening for term signals

Is there something else I am missing?
