### ISSUE TITLE
DeviceSpec is empty in ContainerAllocateResponse starting from v3.3 tag

### ISSUE THREAD

**Issue by blackgold** [k8snetworkplumbingwg/sriov-network-device-plugin#322]
### What happened?
In v3.2, with following configuration
```
{
  "resourceList": [
    {
      "isRdma": true,
      "resourceName": "mlnx_sriov_rdma1",
      "selectors": {
        "pfNames": [
          "ibp12s0#0-0"
        ]
      }
    },
```
ContainerAllocateResponse was sending DeviceSpec

```
I0209 23:50:43.868197  483285 server.go:123] AllocateResponse send: &AllocateResponse{ContainerResponses:[]*ContainerAllocateResponse{&ContainerAllocateResponse{Envs:map[string]string{PCIDEVICE_INTEL_COM_MLNX_SRIOV_RDMA6: 0000:94:00.1,},Mounts:[]*Mount{},
Devices:[]*DeviceSpec{&DeviceSpec{ContainerPath:/dev/infiniband/issm20,HostPath:/dev/infiniband/issm20,Permissions:rwm,},&DeviceSpec{ContainerPath:/dev/infiniband/umad20,HostPath:/dev/infiniband/umad20,Permissions:rwm,},&DeviceSpec{ContainerPath:/dev/infiniband/uverbs20,HostPath:/dev/infiniband/uverbs20,Permissions:rwm,},&DeviceSpec{ContainerPath:/dev/infiniband/rdma_cm,HostPath:/dev/infiniband/rdma_cm,Permissions:rwm,},},Annotations:map[string]string{},},},}
```

Starting v3.3 tag, DeviceSpec is empty. This results in missing /dev/infiniband  path user containers. 
When /dev/infiniband/* paths are missing, user level libraries cannot communicate with mlnx_core module. Hence they don't see rdma devices and distributed training jobs fail to communicate.

### What did you expect to happen?
Expect the newer device plugin released to work with a configuration that works for v3.2 tag.

### What are the minimal steps needed to reproduce the bug?
mellanox connectx-6 card. Configure a virtual function. Replace the vf name in above configuration.
Use device plugin version > v3.2

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |v3.2|
|SR-IOV CNI Plugin            |<Input Version Here>|
|Multus                       |<Input Version Here>|
|Kubernetes                   |<Input Version Here>| 
|OS                           |<Input Version Here>|

### Config Files
Config file locations may be config dependent.

**Comment by adrianchiris** [comment]
> Starting v3.3 tag, DeviceSpec is empty. This results in missing /dev/infiniband path user containers.
When /dev/infiniband/* paths are missing, user level libraries cannot communicate with mlnx_core module. Hence they don't see rdma devices and distributed training jobs fail to communicate.

@blackgold just to make sure i understand in both v3.2 and v3.3 device plugin reports exactly 1 resource (vf index 0), but when a pod is scheduled (and running), v3.3 does not provide mounts for rdma devices in `DeviceSpec` for the allocated VF?

**Comment by blackgold** [comment]
> @blackgold just to make sure i understand, in both v3.2 and v3.3 device plugin reports exactly 1 resource (vf index 0), but when a pod is scheduled (and running), v3.3 does not provide mounts for rdma devices in `DeviceSpec` for the allocated VF?
yes

**Comment by moshe010** [comment]
it because we break the api between v3.2 and v3.3 in v3.3 the isRDMA move to be instead the selectors 
so this should work: 
{
  "resourceList": [
    {
      "resourceName": "mlnx_sriov_rdma1",
      "selectors": {
      "isRdma": true,
        "pfNames": [
          "ibp12s0#0-0"
        ]
      }
    },

Is the complain about the break of api without backport compatible?

**Comment by blackgold** [comment]
well I did not know the break of api.  Looks like the examples in readme is also updated.
Thank you. Closing.
