### ISSUE TITLE
VF return error when use ip command to add vlan id

### ISSUE THREAD

**Issue by antzjm** [k8snetworkplumbingwg/sriov-network-device-plugin#337]
### What happened?
When I launched a pod with `SRIOV` vfs, I meet some problem. When I execute `ip link add link test6 name test6.1526 type vlan id 1526` command, return `RTNETLINK answers: Input/output error` info.
So I find PCI number of error VF and use dpdk command to rebinding VF.
sudo dpdk-devbind --bind=vfio-pci 0000:17:0d.6
sudo dpdk-devbind --bind=iavf 0000:17:0d.6
### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin   |3.1.0-0|
|SR-IOV CNI Plugin                       |danm| 
|Kubernetes                                  |v1.16.2|
|OS                                                |CentOS Linux release 7.8.2003 (Core)|

### Config Files
Config file locations may be config dependent.

##### Device pool config file location (Try '/etc/pcidp/config.json')
{
    "resourceList": [
        {
            "resourceName": "sriov_ens1f1",
            "rootDevices": [
                "17:00.1"
            ],
            "selectors": {
                "drivers": [
                    "mlx5_core",
                    "iavf",
                    "i40evf",
                    "ixgbevf",
                    "igbvf"
                ],
                "pfNames": [
                    "ens1f1"
                ]
            }
        },
        {
            "resourceName": "sriov_vfio_ens1f1",
            "rootDevices": [
                "17:00.1"
            ],
            "selectors": {
                "drivers": [
                    "vfio-pci"
                ],
                "pfNames": [
                    "ens1f1"
                ]
            }
        },
        {
            "resourceName": "sriov_ens11f0",
            "rootDevices": [
                "b3:00.0"
            ],
            "selectors": {
                "drivers": [
                    "mlx5_core",
                    "iavf",
                    "i40evf",
                    "ixgbevf",
                    "igbvf"
                ],
                "pfNames": [
                    "ens11f0"
                ]
            }
        },
        {
            "resourceName": "sriov_vfio_ens11f0",
            "rootDevices": [
                "b3:00.0"
            ],
            "selectors": {
                "drivers": [
                    "vfio-pci"
                ],
                "pfNames": [
                    "ens11f0"
                ]
            }
        }
    ]
}
##### CNI config (Try '/etc/cni/net.d/')
{
  "name": "meta_cni",
  "type": "danm",
  "cniVersion": "0.3.1",
  "kubeconfig": "/etc/kubernetes/kubeconfig/danmc.yml",
  "cniDir": "/etc/cni/net.d"
}

{
  "name": "cbr0",
  "type": "flannel",
  "cniVersion": "0.3.1",
  "delegate": {
    "hairpinMode": true,
    "isDefaultGateway": true
  }
}
##### Kubernetes deployment type ( Bare Metal, Kubeadm etc.)
Bare Metal

**Comment by zshi-redhat** [comment]
> ### What happened?
> 
> When I launched a pod with `SRIOV` vfs, I meet some problem. When I execute `ip link add link test6 name test6.1526 type vlan id 1526` command, return `RTNETLINK answers: Input/output error` info.
> So I find PCI number of error VF and use dpdk command to rebinding VF.
> sudo dpdk-devbind --bind=vfio-pci 0000:17:0d.6
> sudo dpdk-devbind --bind=iavf 0000:17:0d.6

Did it work after rebinding the driver?
Is the cmd executed inside container? If so , you might need extra capabilities add to the pod in order to run the ip cmd inside container. you could try `privileged: true` first.

**Comment by antzjm** [comment]
@zshi-redhat  It works fine after rebinding the driver. I execute ip cmd inside container and container's previlege is ok. I just want to know is there any method to detect such error VF previously.

**Comment by martinkennelly** [comment]
@antzjm Did this issue go away? I don't think we have a method to detect this issue beforehand. I am closing for now because it doesn't seem to be a bug in our software.
