### ISSUE TITLE
dpdk cannot read hw_counters on pod

### ISSUE THREAD

**Issue by ke-jin363** [k8snetworkplumbingwg/sriov-network-device-plugin#345]
in current implementation, seams there is no mount below path into pod for Mallenox NIC, so DPDK cannot read the correct counters.
/sys/bus/pci/devices/0000\:00\:09.0/infiniband/mlx5_0/ports/1/hw_counters/

## What would you like to be added?
if is there a plan to support this or any other way to make DPDK read correct counters?

**Comment by ke-jin363** [comment]
hello, any update? thanks

**Comment by moshe010** [comment]
It depend on the kernel/ofed you are using. I new kernel it  is only supported when using rdma namespace aware in rdma system set netns exclusive.
Please use https://github.com/Mellanox/rdma-cni to use  rdma namespace aware.
If you have issue with the backward compatible that is not working in rdma shared please open nvidia case. I raised it before but the kernel said it not worth to fix.

**Comment by ke-jin363** [comment]
@moshe010 thanks for your reply. i will check how to use rdma-cni. but it's better to mount ports/1/hw_counters into pod without add more CNI.

**Comment by adrianchiris** [comment]
@ke-jin363 did rdma-cni sort the issue for you ?

**Comment by ke-jin363** [comment]
@adrianchiris there is no need to introduce a new cni just due to counter, so i have not spend much time on it.  our final solution is mount /sys/ into other catalog  in pod instead of /sys. how do you think sriov-network-device-plguin cni mount the correct catalog?

**Comment by adrianchiris** [comment]
Explicitly mounting /sys/ might do the trick but exposes all sysfs to the Pod.

I didnt follow you on
> how do you think sriov-network-device-plguin cni mount the correct catalog?

can you elaborate ?

**Comment by moshe010** [comment]
@ke-jin363  it not just for counter it is to make RDMA secure by having the notion of namespace.

**Comment by ke-jin363** [comment]
@moshe010 yes, RDMA cni maybe has more functionality, but we just want to get the correct counter, so no need to use it.

@adrianchiris sorry for confuse you. mount /sys is just a workaround. i mean if sriov-device plgugin cni could mount the corresponding directory of the port, e.g. /sys/bus/pci/devices/0000:00:09.0/infiniband/mlx5_0/ports/1/hw_counters/, not mount /sys, as sriov-device plgugin cni know the prefix directory(/sys/bus/pci/devices/0000:00:09.0) of port it managed.

**Comment by adrianchiris** [comment]
To my understanding, with kernel < `5.3.0` prior to kernel support for network namespace for RDMA resources, these RDMA counters where available (as in visible for all containers). however after support was introduced, these are no longer visible, even if RDMA network namespace mode is set to "shared" (default).

when RDMA network namespace mode is set to "exclusive", in addition to the security benefits, the kernel should expose these counters of a specific RDMA device, given it is moved to the container network namespace (via RDMA CNI).

making these counters truly "shared" is a kernel change IMO and should not be directly addressed by device plugin.

**Comment by ke-jin363** [comment]
@adrianchiris got it, thanks for your reply
