### ISSUE TITLE
failed to support virtio-pci vf.

### ISSUE THREAD

**Issue by chunxiao369** [k8snetworkplumbingwg/sriov-network-device-plugin#352]
## What issue would you like to bring attention to?

error as following,
error adding container to network "virtio-network": SRIOV-CNI failed to load netconf: LoadConf():  failed to get VF information: "lstat /sys/bus/pci/devices/0000:06:00.6/physfn/net: no such file or directory"

I add this resource to configMap.yaml.
{
                "resourceName": "virtionet",
                "resourcePrefix": "intel.com",
                "selectors": {
                    "vendors": ["1af4"],
                    "devices": ["1000"],
                    "pciAddresses": ["0000:06:00.5", "0000:06:00.6"]
                }
}

**Comment by pperiyasamy** [comment]
@chunxiao369 can you try to use host-device for virtio device ? This issue is addressed [there](https://github.com/containernetworking/plugins/pull/453).

**Comment by chunxiao369** [comment]
Thanks, use host-device cni is OK now.

**Comment by chunxiao369** [comment]
fixed

**Comment by BurlyLuo** [comment]
i thinks the virtio can be fine to act as vf.
we can bind vfio-pci driver in our env.
