### ISSUE TITLE
Allow DP to be imported and used a library

### ISSUE THREAD

**Issue by martinkennelly** [k8snetworkplumbingwg/sriov-network-device-plugin#353]
I want to know if the community would like to enable importation of this device plugin (DP) pkgs.

I have folks who want to reuse some of DPs packages and import them - mainly utils. Currently, it is not possible to import packages from this DP using ```go get ...``` for versions 2.0 or greater:

> A package that has opted in to modules must include the major version in the import path to import any v2+ modules
To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of example.com/m must instead use module path example.com/m/v2.

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

Multus had this issue previously here and there are numerous options IF we want to do this. See [here](https://github.com/k8snetworkplumbingwg/multus-cni/issues/504).

Easiest solution is to change the current go.mod module path to ```gopkg.in/k8snetworkplumbingwg/sriov-network-device-plugin.v3```
Now ```go get ...``` works automatically for v1, v2, v3. See example gopkg.in page for this DP [here](https://gopkg.in/martinkennelly/sriov-network-device-plugin.v3) that I created from my personal github using this DP.

We would also have to change all the imports for this DP in the packages e.g:
```github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/resources -> gopkg.in/k8snetworkplumbingwg/sriov-network-device-plugin.v3/resources```

**Comment by adrianchiris** [comment]
if we do that, we would need to pay special attention to changes in any of the packages in the project.
currently the only concern we have is the user-facing APIs.
refactoring is going to be hard.

much of the packages are really project specific IMO perhaps [internal packages](https://golang.org/doc/go1.4#internalpackages) can be used for the ones we do not want to expose. Is it just utils package you want to reuse in other projects ? A point for thought would be whether or not there is enough "critical mass" for it to be worth exposing.

**Comment by martinkennelly** [comment]
We discussed this at the [community meeting](https://docs.google.com/document/d/1bEyEh_K9lGwQWHgUHUH-vqodYd1W-LCWRGlW0-ZVR5A/edit#). Conclusion is we will not expose the internal packages for now due to a lack of demand for it from users and not enough critical mass of code in this DP to export. We are concerned attaining clients of a DP lib and the limitation it would have on refactors.

Suggest to pull using git commit hash (instead of tag) or copy-paste code if only a handful of functions needed. We will revisit if we get additional requests.

**Comment by rpieczon** [comment]
What do you mean by 'internal packages'? All packages existing under `pkg` directory seems to be public.
