### ISSUE TITLE
Exclusive pooling

### ISSUE THREAD

**Issue by martinkennelly** [k8snetworkplumbingwg/sriov-network-device-plugin#355]
## What would you like to be added?
Enable validation that a VF is only used in one resource pool. 

## What is the use case for this feature / enhancement?
Avoid scenario where a VF is in multiple resource pools. VF maybe consumed in one pool and available in another. Attempt to consume VF in additional pools will fail.
This will allow feedback for a bad configmap.

Thanks to @ahalim-intel  !

**Comment by ipatrykx** [comment]
As I believe it would be fine feature I am wondering how this should be implemented. So here are my thoughts:

1. Should it be optional to not change the current behaviour (users can have their configs that would be interrupting with this feature)?
2. How to enable that? Should there be e.g. global `exclusive: true` flag in the config to treat all the pools as `exclusive` or just some pools should be tagged as 'exclusive'?
3. What should be the precedence of the pools? What I mean is, if the device fulfill selectors of multiple pools which one should be chosen by DP? Should it be the first pool in the config map that the device fits in, or should we add some kind of pool priority parameter?

**Comment by ahalimx86** [comment]
> As I believe it would be fine feature I am wondering how this should be implemented. So here are my thoughts:
> 
> 1. Should it be optional to not change the current behaviour (users can have their configs that would be interrupting with this feature)?

I doubt this is desirable behavior in any usecases where user would like to have VFs overlapping on multiple pools. If someone's existing configMap allows that then it is most likely a bad configuration as @martinkennelly outlined above.

> 2. How to enable that? Should there be e.g. global `exclusive: true` flag in the config to treat all the pools as `exclusive` or just some pools should be tagged as 'exclusive'?

There are two options:
    i). VFs should exclusive to a single pool only
    ii). Allow overlap i.e. a VF on multiple pool. 

For ii), once a VF is allocate through one endpoint/pool it should be removed from all other pools it may have included and device  plugin send updated device list again to the kubelet 'device manager'

So, a flag is not needed I suppose.
  

> 3. What should be the precedence of the pools? What I mean is, if the device fulfill selectors of multiple pools which one should be chosen by DP? Should it be the first pool in the config map that the device fits in, or should we add some kind of pool priority parameter?

As resource pools are ordered list, if a VF selected by a pool already it should be removed from the 'global' device list for subsequent pass to other pool(this is for option i) above ) when device pools are created.

For option ii) - trigger update after removing the allocated VF from a pool's device list once this is allocated by another pool. There is slight possibility of race condition here.

**Comment by Eoghan1232** [comment]
As Discussed in the NPWG meeting: 

Gonna go with Scenario 1: 
Add to single resource pool. e.g. pool 1. 
If attempting to add to pool 2 let’s say, then just log it as a warning. And don’t add to pool 2. 

Add VF into first pool it matches, then rest of pools it will be excluded. 

It will mean that a tighter ConfigMap will be needed if it gets added to the wrong resource pool.

**Comment by Eoghan1232** [comment]
Closing as PR is merged.
