### ISSUE TITLE
Using multiple pools in a virtualized deployment

### ISSUE THREAD

**Issue by bjeremy23** [k8snetworkplumbingwg/sriov-network-device-plugin#361]
I understand that a virtualized deployment does not support all selectors available since the pf - vf association is unknown. However, the section on Virtual Deployment Support states that we can use the common selector pciAddress. 

If I have 4 pci and am using two networks, I would like to create two pools, one for each network. For example

          "resourceList": [
              {
                  "resourceName": "sr1",
                  "selectors": {
                      "vendors": ["8086"],
                      "devices": ["154c", "10ed"],
                      "drivers": ["vfio-pci"],
                      "pciAddresses": ["00:06.0","00:07.0"]
                  }
              },
              {
                  "resourceName": "sr2",
                  "selectors": {
                      "vendors": ["8086"],
                      "devices": ["154c", "10ed"],
                      "drivers": ["vfio-pci"],
                      "pciAddresses": ["00:08.0","00:09.0"]
                  }
              }

However, it seems that the pciAddress selector is not being used and all four pci addresses are being place into each pool.

```
W0712 19:26:43.105213 2131075 pciNetDevice.go:61] unable to get PF name "open /sys/bus/pci/devices/0000:00:06.0/net: no such file or directory"
I0712 19:26:43.105284 2131075 manager.go:220] discoverDevices(): device found: 0000:00:07.0 02 Intel Corporation Ethernet Virtual Function 700 Series
W0712 19:26:43.105329 2131075 pciNetDevice.go:61] unable to get PF name "open /sys/bus/pci/devices/0000:00:07.0/net: no such file or directory"
I0712 19:26:43.105390 2131075 manager.go:220] discoverDevices(): device found: 0000:00:08.0 02 Intel Corporation Ethernet Virtual Function 700 Series
W0712 19:26:43.105433 2131075 pciNetDevice.go:61] unable to get PF name "open /sys/bus/pci/devices/0000:00:08.0/net: no such file or directory"
I0712 19:26:43.105495 2131075 manager.go:220] discoverDevices(): device found: 0000:00:09.0 02 Intel Corporation Ethernet Virtual Function 700 Series
W0712 19:26:43.105542 2131075 pciNetDevice.go:61] unable to get PF name "open /sys/bus/pci/devices/0000:00:09.0/net: no such file or directory"
.....
I0712 19:26:43.105617 2131075 manager.go:112] Creating new ResourcePool: sr1
I0712 19:26:43.105625 2131075 factory.go:100] device added: [pciAddr: 0000:00:06.0, vendor: 8086, device: 154c, driver: vfio-pci]
I0712 19:26:43.105629 2131075 factory.go:100] device added: [pciAddr: 0000:00:07.0, vendor: 8086, device: 154c, driver: vfio-pci]
I0712 19:26:43.105631 2131075 factory.go:100] device added: [pciAddr: 0000:00:08.0, vendor: 8086, device: 154c, driver: vfio-pci]
I0712 19:26:43.105634 2131075 factory.go:100] device added: [pciAddr: 0000:00:09.0, vendor: 8086, device: 154c, driver: vfio-pci]
I0712 19:26:43.105643 2131075 manager.go:126] New resource server is created for sr1 ResourcePool
I0712 19:26:43.105648 2131075 manager.go:111]
I0712 19:26:43.105650 2131075 manager.go:112] Creating new ResourcePool: sr2
I0712 19:26:43.105657 2131075 factory.go:100] device added: [pciAddr: 0000:00:06.0, vendor: 8086, device: 154c, driver: vfio-pci]
I0712 19:26:43.105660 2131075 factory.go:100] device added: [pciAddr: 0000:00:07.0, vendor: 8086, device: 154c, driver: vfio-pci]
I0712 19:26:43.105663 2131075 factory.go:100] device added: [pciAddr: 0000:00:08.0, vendor: 8086, device: 154c, driver: vfio-pci]
I0712 19:26:43.105666 2131075 factory.go:100] device added: [pciAddr: 0000:00:09.0, vendor: 8086, device: 154c, driver: vfio-pci]
I0712 19:26:43.105671 2131075 manager.go:126] New resource server is created for sr2 ResourcePool
```

Is there a proper way to do this, or is using the pic address of the vf not supported?

**Comment by adrianchiris** [comment]
Hi @bjeremy23 , this should work AFAIK. what version of device plugin are you using ? you need version `V3.3` or newer

**Comment by bjeremy23** [comment]
Ahh... I'm using 3.2... let me give 3.3 a try... thanks

**Comment by bjeremy23** [comment]
I tried v3.3 and actually it was a little worse results... now instead of all four pci in both pools... now no pci was in either.

Maybe I didn't communicate what I was wanting to do. The pci I was trying to use is for the VF. I just want two pools with the ability to put the VFs in either pool. Is that possible in a virtualized environment?

**Comment by zshi-redhat** [comment]
> I tried v3.3 and actually it was a little worse results... now instead of all four pci in both pools... now no pci was in either.
> 
You may want to try the full pci address ID in the config.json such as: `0000:00:06.0`.
The device will only be selected when pciAddresses filter contains the entire device PCI ID.

**Comment by bjeremy23** [comment]
Thanks for the response. However, that was actually already tried earlier. I did notice the particular config.json that I cut and pasted didn't have that though. Regardless, there was no difference. The outcome was the same.

It seems that the pciAddresses are only for pf devices? I'm not really sure what the difference then is between pciAddresses and rootDevices as a selector other than with rootDevices you can optionally choose the vf to join the pool?

**Comment by bjeremy23** [comment]
Zshi,

Good catch... yeah that was it. I actually thought I caught that earlier... but as luck would have it... I still made the same mistake.  But that was problem after I went to 3.3

Thanks again.

**Comment by martinkennelly** [comment]
Maybe opportunity to validate the PCI address. 
Seems your issue is fixed. Closing.
