### ISSUE TITLE
PF/VF health monitoring

### ISSUE THREAD

**Issue by TothFerenc** [k8snetworkplumbingwg/sriov-network-device-plugin#363]
### What happened?

It is mentioned in the documentation that SR-IOV Network Device Plugin monitors the link statuses:
> Detects Link status (for Linux network devices) and updates associated VFs health accordingly

### What did you expect to happen?

Prevent Pods to get non-healthy VFs.
Affected Pods should be evicted to get healthy VFs.

### What are the minimal steps needed to reproduce the bug?

Set a PF/VF link down.
But nothing happens. SRIOVDP does not detect the change (at least it is not logged), available VF count is not decreased.

In the code I can see that the VF resources are initialized as Healthy, but I do not see any code responsible for updating its status periodically. Is it really a working feature or has not been implemented yet?
Thanks!

**Comment by adrianchiris** [comment]
#362

**Comment by TothFerenc** [comment]
Oh, you were faster a bit.
Let's close this as dup of #362
