### ISSUE TITLE
vfio-pci Kernel 5.4

### ISSUE THREAD

**Issue by infinitydon** [k8snetworkplumbingwg/sriov-network-device-plugin#364]
## What issue would you like to bring attention to?
It seems the way kernel 5.4 (and later) deals with the **_vfio-pci_** is a bit different (VFIO module is included in the kernel from kernel 5.4.26) and I checked the following doc:

https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/master/docs/dpdk/README-virt.md

I was able to confirm that my HW supports IOMMU but the output of `ls /dev/vfio`  just gives **_vfio_** instead of:

```
/dev/vfio/noiommu-0
/dev/vfio/noiommu-1
```
I have done the recommended step in the link that I stated above but still can't find the vfio devices in the VM.

Can someone kindly confirm if there is some other procedure to use if Kernel >= 5.4 is been used?

**Comment by infinitydon** [comment]
I think this might be because I am using **_Intel Corporation Ethernet Connection X553_**.

Does this mean that Intel X553 network adapters can be used?

**Comment by zshi-redhat** [comment]
@Eoghan1232 @ipatrykx @MichalGuzieniuk  any ideas?

**Comment by Eoghan1232** [comment]
Since the VFIO module is included in the kernel from kernel 5.4.26, I believe it is necessary to specify it with the kernel parameter of grub.
/etc/default/grub

Not sure if this is right. just an observation.

**Comment by infinitydon** [comment]
Thanks @Eoghan1232 - Can the Intel Corporation Ethernet Connection X553 use vfio-pci driver also? Because this is what I see when I query the driver modules:

```
05:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Connection X553 10 GbE SFP+ [8086:15c4] (rev 11)
        Subsystem: Intel Corporation Ethernet Connection X553 10 GbE SFP+ [8086:0000]
        Kernel driver in use: ixgbe
        Kernel modules: ixgbe
05:00.1 Ethernet controller [0200]: Intel Corporation Ethernet Connection X553 10 GbE SFP+ [8086:15c4] (rev 11)
        Subsystem: Intel Corporation Ethernet Connection X553 10 GbE SFP+ [8086:0000]
        Kernel driver in use: ixgbe
        Kernel modules: ixgbe
07:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Connection X553 1GbE [8086:15e4] (rev 11)
        Subsystem: Intel Corporation Ethernet Connection X553 1GbE [8086:0000]
        Kernel driver in use: ixgbe
        Kernel modules: ixgbe
07:00.1 Ethernet controller [0200]: Intel Corporation Ethernet Connection X553 1GbE [8086:15e4] (rev 11)
        Subsystem: Intel Corporation Ethernet Connection X553 1GbE [8086:0000]
        Kernel driver in use: ixgbe
        Kernel modules: ixgbe
```

**Comment by Eoghan1232** [comment]
> Thanks @Eoghan1232 - Can the Intel Corporation Ethernet Connection X553 use vfio-pci driver also? Because this is what I see when I query the driver modules:
> 
> ```
> 05:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Connection X553 10 GbE SFP+ [8086:15c4] (rev 11)
>         Subsystem: Intel Corporation Ethernet Connection X553 10 GbE SFP+ [8086:0000]
>         Kernel driver in use: ixgbe
>         Kernel modules: ixgbe
> 05:00.1 Ethernet controller [0200]: Intel Corporation Ethernet Connection X553 10 GbE SFP+ [8086:15c4] (rev 11)
>         Subsystem: Intel Corporation Ethernet Connection X553 10 GbE SFP+ [8086:0000]
>         Kernel driver in use: ixgbe
>         Kernel modules: ixgbe
> 07:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Connection X553 1GbE [8086:15e4] (rev 11)
>         Subsystem: Intel Corporation Ethernet Connection X553 1GbE [8086:0000]
>         Kernel driver in use: ixgbe
>         Kernel modules: ixgbe
> 07:00.1 Ethernet controller [0200]: Intel Corporation Ethernet Connection X553 1GbE [8086:15e4] (rev 11)
>         Subsystem: Intel Corporation Ethernet Connection X553 1GbE [8086:0000]
>         Kernel driver in use: ixgbe
>         Kernel modules: ixgbe
> ```

I currently don't have a X550 series NIC to test this on, but I believe it should.
Have you used the DPDK script to try and bind the driver to the VF?

**Comment by ipatrykx** [comment]
Hi @infinitydon! Thanks for starting this discussion. I also believe that X550 should support VFIO-PCI. You can check that with dpdk-devbind.py -s when the driver is loaded. It should be listed next to your X550 card as unused driver, smiliar to this output here (end of the line):

```
000:FF:00.0 'Ethernet Controller X710 for 10GbE SFP+' if=ens757f0 drv=i40e unused=vfio-pci
```

Are you sure that the device is really binded to the vfio-pci driver and there are no errors? I have 2 machines with CentOS 7. One is running the default 3.10 kernel, and another one is 5.12 from el-repo. It turned out, that the 5.12 Kernel installed from el-repo simply does not support no-iommu feature as it was not compiled with proper flag to do so:

```
user@5.12~ $ uname -r
5.12.4-1.el7.elrepo.x86_64
user@5.12~ $ cat /boot/config-$(uname -r) | grep NOIOMMU
# CONFIG_VFIO_NOIOMMU is not set

user@3.10~ $ uname -r
3.10.0-1160.31.1.el7.x86_64
user@3.10~ $ cat /boot/config-$(uname -r) | grep NOIOMMU
CONFIG_VFIO_NOIOMMU=y
```

Could you please confirm that the kernel you are using can support the no-iommu mode?

**Comment by infinitydon** [comment]
@ipatrykx - Thanks for the response, below shows some of the status on my server:

```
chris@ebenezer:~$ cat /boot/config-$(uname -r) | grep NOIOMMU
CONFIG_VFIO_NOIOMMU=y

chris@ebenezer:~$ uname -r
5.4.0-65-generic
```

On the host system, I am able to bind to the vfio-pci (after I installed ubuntu server, I was using proxmox before):

```
chris@ebenezer:~$ ./dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:05:00.0 'Ethernet Connection X553 10 GbE SFP+ 15c4' drv=vfio-pci unused=ixgbe
0000:05:00.1 'Ethernet Connection X553 10 GbE SFP+ 15c4' drv=vfio-pci unused=ixgbe

Network devices using kernel driver
===================================
0000:02:00.0 'I350 Gigabit Network Connection 1521' if=eno3 drv=igb unused=vfio-pci
0000:02:00.1 'I350 Gigabit Network Connection 1521' if=eno4 drv=igb unused=vfio-pci
0000:02:00.2 'I350 Gigabit Network Connection 1521' if=eno1 drv=igb unused=vfio-pci *Active*
0000:02:00.3 'I350 Gigabit Network Connection 1521' if=eno2 drv=igb unused=vfio-pci
0000:04:00.0 'QCA986x/988x 802.11ac Wireless Network Adapter 003c' if=wlp4s0 drv=ath10k_pci unused=vfio-pci
0000:07:00.0 'Ethernet Connection X553 1GbE 15e4' if=eno6 drv=ixgbe unused=vfio-pci
0000:07:00.1 'Ethernet Connection X553 1GbE 15e4' if=eno5 drv=ixgbe unused=vfio-pci

chris@ebenezer:~$ ls /dev/vfio
20  21  vfio
chris@ebenezer:~$
```

But when I passed through one of the interfaces into a VM (running via kvm), I could not bind the interface to vfio-pci driver:

```
chris@5gcore-worker-edge-01:~$ dpdk-stable-20.11.2/usertools/dpdk-devbind.py -s

Network devices using kernel driver
===================================
0000:01:00.0 'Virtio network device 1041' if=enp1s0 drv=virtio-pci unused=vfio-pci *Active*
0000:06:00.0 'Ethernet Connection X553 10 GbE SFP+ 15c4' if=enp6s0 drv=ixgbe unused=vfio-pci

No 'Baseband' devices detected
==============================


chris@5gcore-worker-edge-01:~$ sudo dpdk-stable-20.11.2/usertools/dpdk-devbind.py -b vfio-pci 0000:06:00.0
[sudo] password for chris:
Error: bind failed for 0000:06:00.0 - Cannot bind to driver vfio-pci
Error: unbind failed for 0000:06:00.0 - Cannot open /sys/bus/pci/drivers//unbind
```

**Comment by infinitydon** [comment]
@ipatrykx - The following worked:

**_sudo echo Y | sudo tee /sys/module/vfio/parameters/enable_unsafe_noiommu_mode_**

After setting that inside the VM, I was able to attach vfio-pci driver to the network interface.

```
chris@5gcore-worker-edge-01:~$ cat /sys/module/vfio/parameters/enable_unsafe_noiommu_mode
N
chris@5gcore-worker-edge-01:~$ sudo dpdk-stable-20.11.2/usertools/dpdk-devbind.py -b vfio-pci 0000:06:00.0
[sudo] password for chris:
Error: bind failed for 0000:06:00.0 - Cannot bind to driver vfio-pci
Error: unbind failed for 0000:06:00.0 - Cannot open /sys/bus/pci/drivers//unbind
chris@5gcore-worker-edge-01:~$
chris@5gcore-worker-edge-01:~$
chris@5gcore-worker-edge-01:~$ sudo echo Y | sudo tee /sys/module/vfio/parameters/enable_unsafe_noiommu_mode
Y
chris@5gcore-worker-edge-01:~$
chris@5gcore-worker-edge-01:~$
chris@5gcore-worker-edge-01:~$ sudo dpdk-stable-20.11.2/usertools/dpdk-devbind.py -b vfio-pci 0000:06:00.0
chris@5gcore-worker-edge-01:~$
chris@5gcore-worker-edge-01:~$
chris@5gcore-worker-edge-01:~$ ls /dev/vfio/
noiommu-0  vfio
```

Maybe this option can also be added to the docs?
