### ISSUE TITLE
can't open /sys/class/uio/uio0/device/config in k8s container when use "--allow-privileged=true"（don‘t volumeMounts /sys)

### ISSUE THREAD

**Issue by yongfeng-liu** [k8snetworkplumbingwg/sriov-network-device-plugin#370]
I use nfvpe/sriov-device-plugin in order to use  vf(whit i40evf ro igb_uio driver) in k8s container.
All functions look like normal except for using vpp in the container.
I tried to use dpdk's test program(testpmd) to see what happened, and found the following problem“

> ./testpmd  -c 10000000 -n 4 --in-memory --file-prefix vpp -w 0000:af:02.1 -w 0000:af:02.3 --master-lcore 28
> EAL: Detected 32 lcore(s)
> EAL: Detected 2 NUMA nodes
> EAL: Selected IOVA mode 'PA'
> EAL: No available hugepages reported in hugepages-1048576kB
> EAL: No free hugepages reported in hugepages-1048576kB
> EAL: No free hugepages reported in hugepages-1048576kB
> EAL: No available hugepages reported in hugepages-1048576kB
> EAL: Probing VFIO support...
> EAL: Using memfd is not supported, falling back to anonymous hugepages
> EAL: PCI device 0000:af:02.1 on NUMA socket 1
> EAL:   probe driver: 8086:154c net_i40e_vf
> **EAL: Cannot open /sys/class/uio/uio0/device/config: Read-only file system**
> EAL: Requested device 0000:af:02.1 cannot be used
> EAL: PCI device 0000:af:02.3 on NUMA socket 1
> EAL:   probe driver: 8086:154c net_i40e_vf
> **EAL: Cannot open /sys/class/uio/uio1/device/config: Read-only file system**
> EAL: Requested device 0000:af:02.3 cannot be used
> testpmd: No probed ethernet devices
> EAL: Error - exiting with code: 1
> Cause: No cores defined for forwarding
> Check the core mask argument
We can see that the error is caused by the permission problem in the container.
I have added "privileged=true"both in kube-apiserver and k8s pod's container.

If I volumeMounts /sys in container’s /sys，testpmd runs normally.

My question is: Is it possible that not to volumeMounts **/sys** and still let the vpp use the VF(**loaded with igb_uio**)  in the container？

I think my operation of the plugin is correct,.
I can see the following information in the container：
> [root@test-pod scripts]# echo $PCIDEVICE_INTEL_COM_INTEL_SRIOV_NETDEVICE_NGU
> **0000:af:02.1**
> [root@test-pod scripts]# echo $PCIDEVICE_INTEL_COM_INTEL_SRIOV_NETDEVICE_CUF1U
> **0000:af:02.3**
and:

> 0000:af:02.1 'XL710/X710 Virtual Function 154c' drv=igb_uio unused=i40evf
> 0000:af:02.3 'XL710/X710 Virtual Function 154c' drv=igb_uio unused=i40evf

**Comment by martinkennelly** [comment]
I don't think you need to mount full /sys fs. You can mount the individual uio device path, so /sys/class/uio/uio1/device but you need to mount that location I believe.
Why not vfio-pci? I don't think you need to mount anything. igb uio is usually not recommended. Any reason why you're using it?

**Comment by yongfeng-liu** [comment]
Thank you for your suggestions.
I tried to use vfio-pci and found that the result is exactly as what you said.
As for why igb_uio is used, just because vfio-pci conflicts with some of private drivers (**this is a my bug**).
