### ISSUE TITLE
Release sriov-network-device-plugin v3.4.0

### ISSUE THREAD

**Issue by e0ne** [k8snetworkplumbingwg/sriov-network-device-plugin#385]
There are [few fixes](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/compare/v3.3.2...master) since the last release. It would be good to make a new release to use it in SR-IOV Network Operator

**Comment by adrianchiris** [comment]
@zshi-redhat @Eoghan1232 id like to release sriov-network-device-plugin.

I think we will target PR #387 for next release. LMK if there are any objections.

**Comment by zshi-redhat** [comment]
> 

Sounds good to me, #387 would need some update and more review.

**Comment by Eoghan1232** [comment]
Agreed. 
#387 still needs some updates.

**Comment by SchSeba** [comment]
+1 we can wait with #387

**Comment by adrianchiris** [comment]
Ack, will proceed with release then.

**Comment by adrianchiris** [comment]
Released 🚀 🚀
