### ISSUE TITLE
no devices in device pool, skipping creating resource server for intel_sriov_netdevice

### ISSUE THREAD

**Issue by newhuangchuan** [k8snetworkplumbingwg/sriov-network-device-plugin#386]
### What happened?
I deploy `sriov-network-device-plugin`, but after the `configMap` is loaded, I deploy `sriovdp` and check the `pod` log of `sriovdp`, it shows
`
I1014 06:06:50.107439       1 manager.go:52] Using Kubelet Plugin Registry Mode
I1014 06:06:50.107722       1 main.go:44] resource manager reading configs
I1014 06:06:50.107799       1 manager.go:86] raw ResourceList: {
    "resourceList": [{
            "resourceName": "intel_sriov_netdevice",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["37cd", "10ed", "1889"],
                "drivers": ["i40evf", "iavf", "ixgbevf"]
            }
        },
        {
            "resourceName": "intel_sriov_dpdk",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["37cd", "10ed", "1889"],
                "drivers": ["vfio-pci"],
                "pfNames": ["eno2v0","eno2v1"]
            }
        },
        {
            "resourceName": "mlnx_sriov_rdma",
            "selectors": {
                "vendors": ["15b3"],
                "devices": ["1018"],
                "drivers": ["mlx5_ib"],
                "isRdma": true
            }
        }
    ]
}
I1014 06:06:50.107833       1 factory.go:168] net device selector for resource intel_sriov_netdevice is &{DeviceSelectors:{Vendors:[8086] Devices:[37cd 10ed 1889] Drivers:[i40evf iavf ixgbevf] PciAddresses:[]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I1014 06:06:50.107851       1 factory.go:168] net device selector for resource intel_sriov_dpdk is &{DeviceSelectors:{Vendors:[8086] Devices:[37cd 10ed 1889] Drivers:[vfio-pci] PciAddresses:[]} PfNames:[eno2v0 eno2v1] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I1014 06:06:50.107863       1 factory.go:168] net device selector for resource mlnx_sriov_rdma is &{DeviceSelectors:{Vendors:[15b3] Devices:[1018] Drivers:[mlx5_ib] PciAddresses:[]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:true NeedVhostNet:false}
I1014 06:06:50.107871       1 manager.go:106] unmarshalled ResourceList: [{ResourcePrefix: ResourceName:intel_sriov_netdevice DeviceType:netDevice Selectors:0xc0002c0f20 SelectorObj:0xc0002ccd00} {ResourcePrefix: ResourceName:intel_sriov_dpdk DeviceType:netDevice Selectors:0xc0002c0f40 SelectorObj:0xc0002cd110} {ResourcePrefix: ResourceName:mlnx_sriov_rdma DeviceType:netDevice Selectors:0xc0002c0f60 SelectorObj:0xc0002cd380}]
I1014 06:06:50.107900       1 manager.go:193] validating resource name "intel.com/intel_sriov_netdevice"
I1014 06:06:50.107913       1 manager.go:193] validating resource name "intel.com/intel_sriov_dpdk"
I1014 06:06:50.107926       1 manager.go:193] validating resource name "intel.com/mlnx_sriov_rdma"
I1014 06:06:50.107931       1 main.go:60] Discovering host devices
I1014 06:06:50.145355       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:00.0 02              Intel Corporation       Ethernet Connection X722 for 1GbE       
I1014 06:06:50.145668       1 netDeviceProvider.go:116] excluding interface eno1:  default route found: {Ifindex: 2 Dst: <nil> Src: <nil> Gw: 10.10.82.1 Flags: [] Table: 254}
I1014 06:06:50.145702       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:00.1 02              Intel Corporation       Ethernet Connection X722 for 1GbE       
I1014 06:06:50.145856       1 netDeviceProvider.go:116] excluding interface eno2:  default route found: {Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.145869       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.0 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146008       1 netDeviceProvider.go:116] excluding interface eno1v0:  default route found: {Ifindex: 30 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146020       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.1 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146135       1 netDeviceProvider.go:116] excluding interface eno1v1:  default route found: {Ifindex: 35 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146154       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.2 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146272       1 netDeviceProvider.go:116] excluding interface eno1v2:  default route found: {Ifindex: 34 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146282       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.3 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146403       1 netDeviceProvider.go:116] excluding interface eno1v3:  default route found: {Ifindex: 33 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146415       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.4 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146533       1 netDeviceProvider.go:116] excluding interface eno1v4:  default route found: {Ifindex: 32 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146543       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.5 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146654       1 netDeviceProvider.go:116] excluding interface eno1v5:  default route found: {Ifindex: 31 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146665       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.6 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146792       1 netDeviceProvider.go:116] excluding interface eno1v6:  default route found: {Ifindex: 37 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146803       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.7 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146912       1 netDeviceProvider.go:116] excluding interface eno1v7:  default route found: {Ifindex: 36 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146922       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.0 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147042       1 netDeviceProvider.go:116] excluding interface eno2v0:  default route found: {Ifindex: 11 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147052       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.1 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147170       1 netDeviceProvider.go:116] excluding interface eno2v1:  default route found: {Ifindex: 4 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147181       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.2 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147337       1 netDeviceProvider.go:116] excluding interface eno2v2:  default route found: {Ifindex: 5 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147352       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.3 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147483       1 netDeviceProvider.go:116] excluding interface eno2v3:  default route found: {Ifindex: 6 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147497       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.4 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147630       1 netDeviceProvider.go:116] excluding interface eno2v4:  default route found: {Ifindex: 7 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147644       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.5 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147776       1 netDeviceProvider.go:116] excluding interface eno2v5:  default route found: {Ifindex: 8 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147789       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.6 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147918       1 netDeviceProvider.go:116] excluding interface eno2v6:  default route found: {Ifindex: 9 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147932       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.7 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.148057       1 netDeviceProvider.go:116] excluding interface eno2v7:  default route found: {Ifindex: 10 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.148083       1 main.go:66] Initializing resource servers
I1014 06:06:50.148089       1 manager.go:112] number of config: 3
I1014 06:06:50.148094       1 manager.go:115] 
I1014 06:06:50.148096       1 manager.go:116] Creating new ResourcePool: intel_sriov_netdevice
I1014 06:06:50.148100       1 manager.go:117] DeviceType: netDevice
I1014 06:06:50.148106       1 manager.go:130] no devices in device pool, skipping creating resource server for intel_sriov_netdevice
I1014 06:06:50.148110       1 manager.go:115] 
I1014 06:06:50.148112       1 manager.go:116] Creating new ResourcePool: intel_sriov_dpdk
I1014 06:06:50.148115       1 manager.go:117] DeviceType: netDevice
I1014 06:06:50.148120       1 manager.go:130] no devices in device pool, skipping creating resource server for intel_sriov_dpdk
I1014 06:06:50.148125       1 manager.go:115] 
I1014 06:06:50.148127       1 manager.go:116] Creating new ResourcePool: mlnx_sriov_rdma
I1014 06:06:50.148130       1 manager.go:117] DeviceType: netDevice
I1014 06:06:50.148135       1 manager.go:130] no devices in device pool, skipping creating resource server for mlnx_sriov_rdma
I1014 06:06:50.148138       1 main.go:72] Starting all servers...
I1014 06:06:50.148142       1 main.go:77] All servers started.
I1014 06:06:50.148146       1 main.go:78] Listening for term signals
`

### What did you expect to happen?
`

Creating new ResourcePool: intel_sriov_netdevice

New resource server is created for intel_sriov_netdevice ResourcePool

Creating new ResourcePool: intel_sriov_dpdk

New resource server is created for intel_sriov_dpdk ResourcePool

Creating new ResourcePool: mlnx_sriov_rdma

New resource server is created for mlnx_sriov_rdma ResourcePool
`
### What are the minimal steps needed to reproduce the bug?
two
### Anything else we need to know?
Currently the kubernetes cluster is deployed, the version is 1.18.5, multus, sriov-cni are deployed, and sriov-network-device-plugin is currently being deployed.
### Component Versions
Please fill in the below table with the version numbers of components used.
Currently the kubernetes cluster is deployed, the version is 1.18.5, multus, sriov-cni are deployed, and sriov-network-device-plugin is currently being deployed.
Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<v3.3.1>|
|SR-IOV CNI Plugin            |<v2.6.1>|
|Multus                       |<v3.8>|
|Kubernetes                   |<v1.18.5>| 
|OS                           |<ubuntu>|

### Config Files
Config file locations may be config dependent.
`
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_netdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["37cd", "10ed", "1889"],
                    "drivers": ["i40evf", "iavf", "ixgbevf"]
                }
            },
            {
                "resourceName": "intel_sriov_dpdk",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["37cd", "10ed", "1889"],
                    "drivers": ["vfio-pci"],
                    "pfNames": ["eno2v0","eno2v1"]
                }
            },
            {
                "resourceName": "mlnx_sriov_rdma",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1018"],
                    "drivers": ["mlx5_ib"],
                    "isRdma": true
                }
            }
        ]
    }
`
##### Device pool config file location (Try '/etc/pcidp/config.json')
The host is not added

##### Kubernetes deployment type ( Bare Metal, Kubeadm etc.)
kubeadm

##### SR-IOV Network Device Plugin Logs (use `kubectl logs $PODNAME`)
`
I1014 06:06:50.107439       1 manager.go:52] Using Kubelet Plugin Registry Mode
I1014 06:06:50.107722       1 main.go:44] resource manager reading configs
I1014 06:06:50.107799       1 manager.go:86] raw ResourceList: {
    "resourceList": [{
            "resourceName": "intel_sriov_netdevice",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["37cd", "10ed", "1889"],
                "drivers": ["i40evf", "iavf", "ixgbevf"]
            }
        },
        {
            "resourceName": "intel_sriov_dpdk",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["37cd", "10ed", "1889"],
                "drivers": ["vfio-pci"],
                "pfNames": ["eno2v0","eno2v1"]
            }
        },
        {
            "resourceName": "mlnx_sriov_rdma",
            "selectors": {
                "vendors": ["15b3"],
                "devices": ["1018"],
                "drivers": ["mlx5_ib"],
                "isRdma": true
            }
        }
    ]
}
I1014 06:06:50.107833       1 factory.go:168] net device selector for resource intel_sriov_netdevice is &{DeviceSelectors:{Vendors:[8086] Devices:[37cd 10ed 1889] Drivers:[i40evf iavf ixgbevf] PciAddresses:[]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I1014 06:06:50.107851       1 factory.go:168] net device selector for resource intel_sriov_dpdk is &{DeviceSelectors:{Vendors:[8086] Devices:[37cd 10ed 1889] Drivers:[vfio-pci] PciAddresses:[]} PfNames:[eno2v0 eno2v1] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I1014 06:06:50.107863       1 factory.go:168] net device selector for resource mlnx_sriov_rdma is &{DeviceSelectors:{Vendors:[15b3] Devices:[1018] Drivers:[mlx5_ib] PciAddresses:[]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:true NeedVhostNet:false}
I1014 06:06:50.107871       1 manager.go:106] unmarshalled ResourceList: [{ResourcePrefix: ResourceName:intel_sriov_netdevice DeviceType:netDevice Selectors:0xc0002c0f20 SelectorObj:0xc0002ccd00} {ResourcePrefix: ResourceName:intel_sriov_dpdk DeviceType:netDevice Selectors:0xc0002c0f40 SelectorObj:0xc0002cd110} {ResourcePrefix: ResourceName:mlnx_sriov_rdma DeviceType:netDevice Selectors:0xc0002c0f60 SelectorObj:0xc0002cd380}]
I1014 06:06:50.107900       1 manager.go:193] validating resource name "intel.com/intel_sriov_netdevice"
I1014 06:06:50.107913       1 manager.go:193] validating resource name "intel.com/intel_sriov_dpdk"
I1014 06:06:50.107926       1 manager.go:193] validating resource name "intel.com/mlnx_sriov_rdma"
I1014 06:06:50.107931       1 main.go:60] Discovering host devices
I1014 06:06:50.145355       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:00.0 02              Intel Corporation       Ethernet Connection X722 for 1GbE       
I1014 06:06:50.145668       1 netDeviceProvider.go:116] excluding interface eno1:  default route found: {Ifindex: 2 Dst: <nil> Src: <nil> Gw: 10.10.82.1 Flags: [] Table: 254}
I1014 06:06:50.145702       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:00.1 02              Intel Corporation       Ethernet Connection X722 for 1GbE       
I1014 06:06:50.145856       1 netDeviceProvider.go:116] excluding interface eno2:  default route found: {Ifindex: 3 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.145869       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.0 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146008       1 netDeviceProvider.go:116] excluding interface eno1v0:  default route found: {Ifindex: 30 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146020       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.1 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146135       1 netDeviceProvider.go:116] excluding interface eno1v1:  default route found: {Ifindex: 35 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146154       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.2 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146272       1 netDeviceProvider.go:116] excluding interface eno1v2:  default route found: {Ifindex: 34 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146282       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.3 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146403       1 netDeviceProvider.go:116] excluding interface eno1v3:  default route found: {Ifindex: 33 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146415       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.4 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146533       1 netDeviceProvider.go:116] excluding interface eno1v4:  default route found: {Ifindex: 32 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146543       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.5 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146654       1 netDeviceProvider.go:116] excluding interface eno1v5:  default route found: {Ifindex: 31 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146665       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.6 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146792       1 netDeviceProvider.go:116] excluding interface eno1v6:  default route found: {Ifindex: 37 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146803       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:02.7 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.146912       1 netDeviceProvider.go:116] excluding interface eno1v7:  default route found: {Ifindex: 36 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.146922       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.0 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147042       1 netDeviceProvider.go:116] excluding interface eno2v0:  default route found: {Ifindex: 11 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147052       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.1 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147170       1 netDeviceProvider.go:116] excluding interface eno2v1:  default route found: {Ifindex: 4 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147181       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.2 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147337       1 netDeviceProvider.go:116] excluding interface eno2v2:  default route found: {Ifindex: 5 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147352       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.3 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147483       1 netDeviceProvider.go:116] excluding interface eno2v3:  default route found: {Ifindex: 6 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147497       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.4 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147630       1 netDeviceProvider.go:116] excluding interface eno2v4:  default route found: {Ifindex: 7 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147644       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.5 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147776       1 netDeviceProvider.go:116] excluding interface eno2v5:  default route found: {Ifindex: 8 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147789       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.6 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.147918       1 netDeviceProvider.go:116] excluding interface eno2v6:  default route found: {Ifindex: 9 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.147932       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.7 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1014 06:06:50.148057       1 netDeviceProvider.go:116] excluding interface eno2v7:  default route found: {Ifindex: 10 Dst: <nil> Src: <nil> Gw: 10.10.254.1 Flags: [] Table: 254}
I1014 06:06:50.148083       1 main.go:66] Initializing resource servers
I1014 06:06:50.148089       1 manager.go:112] number of config: 3
I1014 06:06:50.148094       1 manager.go:115] 
I1014 06:06:50.148096       1 manager.go:116] Creating new ResourcePool: intel_sriov_netdevice
I1014 06:06:50.148100       1 manager.go:117] DeviceType: netDevice
I1014 06:06:50.148106       1 manager.go:130] no devices in device pool, skipping creating resource server for intel_sriov_netdevice
I1014 06:06:50.148110       1 manager.go:115] 
I1014 06:06:50.148112       1 manager.go:116] Creating new ResourcePool: intel_sriov_dpdk
I1014 06:06:50.148115       1 manager.go:117] DeviceType: netDevice
I1014 06:06:50.148120       1 manager.go:130] no devices in device pool, skipping creating resource server for intel_sriov_dpdk
I1014 06:06:50.148125       1 manager.go:115] 
I1014 06:06:50.148127       1 manager.go:116] Creating new ResourcePool: mlnx_sriov_rdma
I1014 06:06:50.148130       1 manager.go:117] DeviceType: netDevice
I1014 06:06:50.148135       1 manager.go:130] no devices in device pool, skipping creating resource server for mlnx_sriov_rdma
I1014 06:06:50.148138       1 main.go:72] Starting all servers...
I1014 06:06:50.148142       1 main.go:77] All servers started.
I1014 06:06:50.148146       1 main.go:78] Listening for term signals

`
##### Kubelet logs (journalctl -u kubelet)
`
10月 11 16:13:18 uos-PC systemd[1]: Started kubelet: The Kubernetes Node Agent.
10月 11 16:13:18 uos-PC systemd[1]: kubelet.service: Current command vanished from the unit file, execution of the command list won't be resumed.
10月 11 16:13:18 uos-PC systemd[1]: Stopping kubelet: The Kubernetes Node Agent...
10月 11 16:13:18 uos-PC systemd[1]: kubelet.service: Main process exited, code=killed, status=15/TERM
10月 11 16:13:18 uos-PC systemd[1]: kubelet.service: Succeeded.
10月 11 16:13:18 uos-PC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
10月 11 16:13:18 uos-PC systemd[1]: Started kubelet: The Kubernetes Node Agent.
10月 11 16:13:18 uos-PC kubelet[26124]: F1011 16:13:18.450046   26124 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/conf
10月 11 16:13:18 uos-PC systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
10月 11 16:13:18 uos-PC systemd[1]: kubelet.service: Failed with result 'exit-code'.
10月 11 16:13:28 uos-PC systemd[1]: kubelet.service: Service RestartSec=10s expired, scheduling restart.
10月 11 16:13:28 uos-PC systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 1.
10月 11 16:13:28 uos-PC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
10月 11 16:13:28 uos-PC systemd[1]: Started kubelet: The Kubernetes Node Agent.
10月 11 16:13:28 uos-PC kubelet[26248]: F1011 16:13:28.697808   26248 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/conf
10月 11 16:13:28 uos-PC systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
10月 11 16:13:28 uos-PC systemd[1]: kubelet.service: Failed with result 'exit-code'.
10月 11 16:13:38 uos-PC systemd[1]: kubelet.service: Service RestartSec=10s expired, scheduling restart.
10月 11 16:13:38 uos-PC systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 2.
10月 11 16:13:38 uos-PC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
10月 11 16:13:38 uos-PC systemd[1]: Started kubelet: The Kubernetes Node Agent.
10月 11 16:13:38 uos-PC kubelet[26304]: F1011 16:13:38.945894   26304 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/conf
10月 11 16:13:38 uos-PC systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
10月 11 16:13:38 uos-PC systemd[1]: kubelet.service: Failed with result 'exit-code'.
10月 11 16:13:49 uos-PC systemd[1]: kubelet.service: Service RestartSec=10s expired, scheduling restart.
10月 11 16:13:49 uos-PC systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 3.
10月 11 16:13:49 uos-PC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
10月 11 16:13:49 uos-PC systemd[1]: Started kubelet: The Kubernetes Node Agent.
10月 11 16:13:49 uos-PC kubelet[26723]: F1011 16:13:49.194664   26723 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/conf
10月 11 16:13:49 uos-PC systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
10月 11 16:13:49 uos-PC systemd[1]: kubelet.service: Failed with result 'exit-code'.
10月 11 16:13:55 uos-PC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
10月 11 16:20:42 uos-PC systemd[1]: Started kubelet: The Kubernetes Node Agent.
10月 11 16:20:42 uos-PC kubelet[29142]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/adm
10月 11 16:20:42 uos-PC kubelet[29142]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/adm
10月 11 16:20:42 uos-PC kubelet[29142]: I1011 16:20:42.911221   29142 server.go:417] Version: v1.18.5
10月 11 16:20:42 uos-PC kubelet[29142]: I1011 16:20:42.911505   29142 plugins.go:100] No cloud provider specified.
10月 11 16:20:42 uos-PC kubelet[29142]: I1011 16:20:42.911523   29142 server.go:837] Client rotation is on, will bootstrap in background
10月 11 16:20:42 uos-PC kubelet[29142]: F1011 16:20:42.911564   29142 server.go:274] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directo
10月 11 16:20:42 uos-PC systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
10月 11 16:20:42 uos-PC systemd[1]: kubelet.service: Failed with result 'exit-code'.
10月 11 16:20:53 uos-PC systemd[1]: kubelet.service: Service RestartSec=10s expired, scheduling restart.
10月 11 16:20:53 uos-PC systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 4.
10月 11 16:20:53 uos-PC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
10月 11 16:20:53 uos-PC systemd[1]: Started kubelet: The Kubernetes Node Agent.
`

**Comment by adrianchiris** [comment]
> About the resource pool intel_sriov_dpdk and mlnx_sriov_rdma did not seem to be created successfully

RE mlnx_sriov_rdma, Are RDMA modules loaded in the system ? it seems according to the logs that the PCI devices (`0000:60:06.X`) dont have RDMA devices. what is the output of `/dev/infiniband` in the system ?

**Comment by adrianchiris** [comment]
> Hello, there is a display on my side, do you think so?

you should load kernel RDMA modules, installing rdma-core package will set-up udev rules to load them when lower level driver loads. 

on my system (with two MLNX ports) i got:
```
[root ~]# ls /dev/infiniband/
issm0  issm1  rdma_cm  umad0  umad1  uverbs0  uverbs1
```


>And is it necessary to specify these three resources (including dpdk), and then the created CRD can be used, when I create a resource pool to use

you can just specify the resources you need.

**Comment by newhuangchuan** [comment]
Currently I have deployed sriov-cni, multus-cni, sriov-network-device, and created a resource pool, but the vm prompt is created
```
Events:
  Type     Reason            Age                 From                       Message
  ----     ------            ----                ----                       -------
  Normal   SuccessfulCreate  96s                 virtualmachine-controller  Created virtual machine pod virt-launcher-vmi-perf-pr5r2
  Warning  SyncFailed        10s (x13 over 21s)  virt-handler, uos-pc       server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: host doesn't support passthrough of host PCI devices')"
```
vfio-pci：
```
$ lsmod | grep vfio
vfio_pci               53248  0
vfio_virqfd            16384  1 vfio_pci
vfio_iommu_type1       28672  0
vfio                   32768  2 vfio_iommu_type1,vfio_pci
irqbypass              16384  2 vfio_pci,kvm
```

**Comment by newhuangchuan** [comment]
Hello, it is possible to create a pod.

**Comment by adrianchiris** [comment]
So new i see:
> unsupported configuration: host doesn't support passthrough of host PCI devices

please see my comment in #389

**Comment by adrianchiris** [comment]
@newhuangchuan can this issue be closed ?

**Comment by newhuangchuan** [comment]
ok, thank you very much.

**Comment by adrianchiris** [comment]
ack, Closing
