### ISSUE TITLE
DHCP container with SRIOV interface

### ISSUE THREAD

**Issue by ShashankNEC** [k8snetworkplumbingwg/sriov-network-device-plugin#391]
Hi Team,

Thanks for your support.

AM trying to run a DHCP server on K8s cluster (single node). CLuster having flannel with multus CNI.
I have run the DHCP container and sucessfully inject my SR-IOV interface on which my DHCP server will start listening.
Used below network attchment for dhcp server pod creation.
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  namespace: kube-system
  name: dhcp-server
  annotations:
    k8s.v1.cni.cncf.io/resourceName: altiostar.com/ani_sriov_netdevice_vf
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "vlan": 3250,
  "ipam": {
    "type": "host-local",
    "subnet": "10.80.235.200/29",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.80.235.201"
  }
}'
Issue:- When i try to run test pod with same network attachment file pods are getting ip's from this 10.80.235.200/29 pool not from DHCP range which i defined in DHCP server.
Please help me where i made the mistake am trying this from last week.

**Comment by Eoghan1232** [comment]
@ShashankNEC Do you want 2 different interfaces attached to the DHCP server?
i.e. right now, you have only 1:
altiostar.com/ani_sriov_netdevice_vf: "1"

**Comment by SchSeba** [comment]
closing this issues last update was 2 months ago
