### ISSUE TITLE
Applying Kubernetes network policies to containers with SR-IOV VF

### ISSUE THREAD

**Issue by edgenfv** [k8snetworkplumbingwg/sriov-network-device-plugin#397]
I am using Kubernetes to create containers mapped with SR-IOV VF. For this purpose, I use [Kubernetes SR-IOV network device plugin](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin). 
Now I need to apply [Kubernetes network policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) to the attached SR-IOV VF. 
Can the SR-IOV network device plugin enforce the network policies to the SR-IOV VF.

**Comment by adrianchiris** [comment]
Hi @edgenfv , enforcing network policies is a k8s network plugin responsibility (CNI)

for secondary network there is:

https://github.com/k8snetworkplumbingwg/multi-networkpolicy
https://github.com/k8snetworkplumbingwg/multi-networkpolicy-iptables

**Comment by SchSeba** [comment]
Hi @edgenfv another comment on the project shared by @adrianchiris this will only work on sriov nics attached to kernel drivers, not DPDK drivers.

**Comment by SchSeba** [comment]
one more comment in the deployment (https://github.com/k8snetworkplumbingwg/multi-networkpolicy-iptables/blob/master/deploy.yml#L99) you need to add this line to support also sriov

```
- "--network-plugins=macvlan,sriov"
```

**Comment by adrianchiris** [comment]
@edgenfv is there any more input you require ?

**Comment by SchSeba** [comment]
no update in about 2 months closing this issue
