### ISSUE TITLE
vhost-user,memif  support

### ISSUE THREAD

**Issue by infinitydon** [k8snetworkplumbingwg/sriov-network-device-plugin#400]
## What issue would you like to bring attention to?
I want to ask if sriov-dp supports exposing vhost-user and memif sockets (which are created by either vpp or ovs-dpdk)?

## What is the impact of this issue?
None

## Do you have a proposed response or remediation for the issue?
I noticed intel userspace-cni has support for this but am not sure if the project is still actively supported (last update was in October 2020)

**Comment by zshi-redhat** [comment]
> I want to ask if sriov-dp supports exposing vhost-user and memif sockets (which are created by either vpp or ovs-dpdk)?

sriov-dp doesn't support vhost-user or memif.

> I noticed intel userspace-cni has support for this but am not sure if the project is still actively supported (last update was in October 2020)

@Billy99 may know the status of userspace-cni project.

**Comment by Billy99** [comment]
@infinitydon Intel Userspace CNI is not being actively supported from my side. I'm not sure what Intel's stance is, but based on activity, I would say they are not supporting it either.

**Comment by infinitydon** [comment]
Thanks @Billy99 - Do you have any suggestion on a similar project that does the same thing?

**Comment by Billy99** [comment]
I don't. There is [ovs-cni](https://github.com/k8snetworkplumbingwg/ovs-cni), but I don't see any vhost-user references in it. [contiv](https://github.com/contiv) was the Cisco driven CNI for VPP. They probably have some memif support, but I haven't used it.

**Comment by infinitydon** [comment]
Thanks Bill, I also noticed calico has a vpp dataplane implementation and they're planning to add memif support, I will keep an on that..
