### ISSUE TITLE
NetworkPlugin cni failed to teardown pod "testpod1_default" 

### ISSUE THREAD

**Issue by krjagan** [k8snetworkplumbingwg/sriov-network-device-plugin#403]
Hi All,

In Bare metal server, we have created VF's then we have deployed anthos (1.8) on bare metal servers later enabled SRIOV device plugin and multus plugin and created network-attached definition then while deploying pod we are getting below issue...

pod logs :-

 Type     Reason                  Age                From               Message
  ----     ------                  ----               ----               -------
  Normal   Scheduled               84s                default-scheduler  Successfully assigned default/testpod1 to anusr2.anthos.jagan.local
  Normal   AddedInterface          83s                multus             Add eth0 [192.168.3.126/32] from portmap
  Warning  FailedCreatePodSandBox  82s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "f0eef33f5608824871a68da03fe95c7a043da356d9cb1b41ba2cd5141dfbfc9e" network for pod "testpod1": networkPlugin cni failed to set up pod "testpod1_default" network: [default/testpod1/:sriov-network]: error adding container to network "sriov-network": failed to find plugin "sriov" in path [/opt/cni/bin /opt/cni/bin], failed to clean up sandbox container "f0eef33f5608824871a68da03fe95c7a043da356d9cb1b41ba2cd5141dfbfc9e" network for pod "testpod1": networkPlugin cni failed to teardown pod "testpod1_default" network: delegateDel: error invoking DelegateDel - "sriov": error in getting result from DelNetwork: failed to find plugin "sriov" in path [/opt/cni/bin /opt/cni/bin]]
  Normal   SandboxChanged          12s (x7 over 82s)  kubelet            Pod sandbox changed, it will be killed and re-created.

kube-system               kube-sriov-device-plugin-amd64-7sv5t                        1/1     Running             0          139m
kube-system               kube-sriov-device-plugin-amd64-8rj42                        1/1     Running             0          139m
kube-system               kube-sriov-device-plugin-amd64-q45hl                        1/1     Running             0          139m

kube-system               kube-multus-ds-gmp5j                                        1/1     Running             0          138m
kube-system               kube-multus-ds-kgt5h                                        1/1     Running             0          138m
kube-system               kube-multus-ds-xfbvd                                        1/1     Running             0          138m

Name:         sriov-net1
Namespace:    default
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/resourceName: marvell.com/marvell_sriov_netdevice
API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2022-01-12T13:51:11Z
  Generation:          1
  Managed Fields:
    API Version:  k8s.cni.cncf.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:k8s.v1.cni.cncf.io/resourceName:
      f:spec:
        .:
        f:config:
    Manager:         kubectl-create
    Operation:       Update
    Time:            2022-01-12T13:51:11Z
  Resource Version:  35501
  UID:               b0ebcc5e-ebe6-4b2f-b9ec-33779c247958
Spec:
  Config:  { "type": "sriov", "cniVersion": "0.3.1", "name": "sriov-network", "ipam": { "type": "host-local", "subnet": "10.56.217.0/24", "routes": [{ "dst": "0.0.0.0/0" }], "gateway": "10.56.217.1" } }
Events:    <none>

Node :- **kubectl get node worker2 -o json | jq '.status.allocatable'**

{
  "cpu": "39430m",
  "ephemeral-storage": "89956417388",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "marvell.com/marvell_sriov_dpdk": "3",
  "marvell.com/marvell_sriov_netdevice": "3",
  "memory": "121944084Ki",
  "pods": "250"
}

Kindly help me out on this .....

**Comment by SchSeba** [comment]
Hi @krjagan did you also deploy the sriov-cni?

**Comment by krjagan** [comment]
Thank you for your response
 
I have followed below steps to create SRIOV plugin:-

1) Created config map ------ kubectl create -f deployments/configMap.yaml
2) Created daemonset  --------------- kubectl create -f deployments/k8s-v1.16/sriovdp-daemonset.yaml
3) Deployed multus ---  cat ./deployments/multus-daemonset-thick-plugin.yml | kubectl apply -f -
4) Created NetworkAttachmentDefinition ---- kubectl create -f deployments/sriov-crd.yaml

**Comment by krjagan** [comment]
Hi SchSeba,

in my nodes, i didn't find **sriov** cni plugin on  **/opt/cni/bin** location

**Comment by Eoghan1232** [comment]
Hi @krjagan ,
Did you do the following step?
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin#install-sr-iov-cni

Install SRIOV-CNI:
https://github.com/k8snetworkplumbingwg/sriov-cni

**Comment by krjagan** [comment]
Yup, I have followed the same 

https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin#install-sr-iov-cni

Install SRIOV-CNI:
https://github.com/k8snetworkplumbingwg/sriov-cni

**Comment by Eoghan1232** [comment]
> Yup, I have followed the same
> 
> https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin#install-sr-iov-cni
> 
> Install SRIOV-CNI: https://github.com/k8snetworkplumbingwg/sriov-cni

Could you do 'kubectl get pods -A' and paste the output here?

**Comment by krjagan** [comment]
Hi Eoghan1232,

Thank you for your support...

Pod started working with the SRIOV cni network after redeploying the cluster and enabling SRIOV.

Do suggest me the tools used for testing the performance between node SRIOV VF and SRIOV CNI.

**Comment by Eoghan1232** [comment]
> Hi Eoghan1232,
> 
> Thank you for your support...
> 
> Pod started working with the SRIOV cni network after redeploying the cluster and enabling SRIOV.
> 
> Do suggest me the tools used for testing the performance between node SRIOV VF and SRIOV CNI.

I'm not sure I understand, I don't think we have tools for this. 
What exactly are you trying to do/achieve?

**Comment by krjagan** [comment]
I want to test network Latency and throughput between sriov interface and node interface. 

And  I'm unable to ping the SRIOV CNI network from the node. Do suggest me to resolve this??

**Comment by adrianchiris** [comment]
For testing latency and bandwidth you can use [iperf](https://iperf.fr/)

sriov cni network is a secondary network, unless specifically configured you cannot access the secondary network from host.
you can reserve one VF for host and assign it an IP address on the same subnet as defined for the sriov secondary network.

alternatively you can assign IP address to the netdev of the physical function (PF) in the same subnet as defined for the secondary network.

**Comment by adrianchiris** [comment]
@krjagan i believe the original issue was configuration issue and not related to sriov-network-device-plugin.
if so please feel free to close this ticket.
