### ISSUE TITLE
Request info on acces to "resourceName"

### ISSUE THREAD

**Issue by bpetto35** [k8snetworkplumbingwg/sriov-network-device-plugin#404]
Not an issue, just a question

On a project I work, the project used SRIOV and one of issue we have is to dynamically assign VLAN to the pods.
VLAN in itself is not a great deal but we need to enumerate the physical name (field "resourceName" of config.json) to write the resources requests and limits of the pod.
need to write:
> intel/{resourceName}: 1 // when VLAN are on 2 NIC
or 
> intel/{resourceName}: 2 // when both VLAN are on the same NIC

So question is: does it exist an API endpoint that allow us to enumarate such things ?
We think to directly use the /etc/pcidp/config.json but don't know if it's a great idea.

Any advices ?

**Comment by adrianchiris** [comment]
Hi,
Are you looking for an automated way to inject pod resources based on the network  ?
https://github.com/k8snetworkplumbingwg/network-resources-injector

if not, then im not sure exactly what info you are looking for, perhaps provide additional info :)

**Comment by bpetto35** [comment]
Hi, not exactly. The app we develop assign cpu and memory resources to its processing pods according to our receipe.
Processing pods take hi-res video/audio input stream and output ip stream.
Customer want us to be able to sub select a VLAN.

We had imagined that VLAN can be defined by a network-attachment-definition and it should be simple for us to rewrite the annotations and resources in the pod definition before deploying it. The only missing parameters is the resourceName.

We had think about put the resourceName in the values.yaml if we can't detect them at runtime. backend pod can't access the /etc/pcidp/config.json as it runs on non-SRIOV node.

We were expecting to send a query to the sriov pods and retrieve a list of resourceName. If not possible, we fallback to read the network-definition-attachment of the NIC

Don't know if I provide enough (it's simple in my mind - not simple to write it on paper), sorry for that

**Comment by SchSeba** [comment]
Hi @bpetto35 let me try here :)

as suggested by @adrianchiris you should can use the network-resource-injector (btw you can take a look at the sriov-network-operator it should deploy all the components for you)

what you will do is to create a config to add all the vfs under a resourceName,  then you create multiple net-attach-def with the vlans you want pointing to the same resourceName.

Then when you want to start a pod on a specific vlan you use the right net-attach-def and the sriov-cni will configure the vlan for that right VF that was moved into your application.

you can even skip the resource-injector and always add the resourceName in the pod resources just like you do with CPU and memory.

**Comment by bpetto35** [comment]
Thnaks guys
