### ISSUE TITLE
Move DeviceInfoSpec struct creation to PciNetDevice

### ISSUE THREAD

**Issue by amorenoz** [k8snetworkplumbingwg/sriov-network-device-plugin#405]
The code that populates DeviceInfoSpec information is currently in `netResourcePool.go` 
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/7488066fa720cb32ae77dd412fa84088f3ebac10/pkg/netdevice/netResourcePool.go#L79-L85

It would be cleaner if it lived in `PciNetDevice`

**Comment by SchSeba** [comment]
we re-struct the project on https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/441
closing this issue feel free to reopen if needed
