### ISSUE TITLE
SRIOV - VF- Metric exposure

### ISSUE THREAD

**Issue by esiperu-est** [k8snetworkplumbingwg/sriov-network-device-plugin#406]
we are looking to pull metrics SRIOV VF interfaces from Prometheus. 

We came across a project in intel-github (https://github.com/intel/sriov-network-metrics-exporter).

This requirement/request was discussed in "K8s Network & Resource Management" on 31/Jan/2022. 

Raising this Enhancement request to track the same.

**Comment by SchSeba** [comment]
The project was moved into the k8snetworkplumbingwg 
https://github.com/k8snetworkplumbingwg/sriov-network-metrics-exporter

we will add support for netlink metrics exporter so it will be a generic solution and integrate this into the sriov-network operator.
Closing this issue here.
