### ISSUE TITLE
Insufficient intel.com/mlnx_sriov_rdma

### ISSUE THREAD

**Issue by eduardocalfaia** [k8snetworkplumbingwg/sriov-network-device-plugin#424]
Hi dears,
I am getting the error bellow 

I am using Mellanox drivers, the devices are founded but BCM57414 NetXtreme-E 10Gb/25Gb RDMA  is used instead.

## What issue would you like to bring attention to?

root@node-0:~# k logs kube-sriov-device-plugin-amd64-28q7r -n kube-system
I0506 16:33:56.758364       1 manager.go:51] Using Kubelet Plugin Registry Mode
I0506 16:33:56.758504       1 main.go:44] resource manager reading configs
I0506 16:33:56.758524       1 manager.go:79] raw ResourceList: {
    "resourceList": [{
            "resourceName": "intel_sriov_netdevice",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["154c", "10ed", "1889"],
                "drivers": ["i40evf", "iavf", "ixgbevf"]
            }
        },
        {
            "resourceName": "intel_sriov_dpdk",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["154c", "10ed", "1889"],
                "drivers": ["vfio-pci"],
                "pfNames": ["enp0s0f0","enp2s2f1"]
            }
        },
        {
            "resourceName": "mlnx_sriov_rdma",
            "selectors": {
                "vendors": ["15b3"],
                "devices": ["0000:41:00.2","0000:41:00.3","0000:41:00.4","0000:41:00.5","0000:41:00.6","0000:41:00.7"],
                "drivers": ["mlx5_ib"],
                "isRdma": true
            }
        }
    ]
}
I0506 16:33:56.758618       1 factory.go:166] net device selector for resource intel_sriov_netdevice is &{DeviceSelectors:{Vendors:[8086] Devices:[154c 10ed 1889] Drivers:[i40evf iavf ixgbevf] PciAddresses:[]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I0506 16:33:56.758646       1 factory.go:166] net device selector for resource intel_sriov_dpdk is &{DeviceSelectors:{Vendors:[8086] Devices:[154c 10ed 1889] Drivers:[vfio-pci] PciAddresses:[]} PfNames:[enp0s0f0 enp2s2f1] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I0506 16:33:56.758664       1 factory.go:166] net device selector for resource mlnx_sriov_rdma is &{DeviceSelectors:{Vendors:[15b3] Devices:[0000:41:00.2 0000:41:00.3 0000:41:00.4 0000:41:00.5 0000:41:00.6 0000:41:00.7] Drivers:[mlx5_ib] PciAddresses:[]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:true NeedVhostNet:false}
I0506 16:33:56.758675       1 manager.go:99] unmarshalled ResourceList: [{ResourcePrefix: ResourceName:intel_sriov_netdevice DeviceType:netDevice Selectors:0xc00000cd38 SelectorObj:0xc0002d1110} {ResourcePrefix: ResourceName:intel_sriov_dpdk DeviceType:netDevice Selectors:0xc00000cd50 SelectorObj:0xc0002d15f0} {ResourcePrefix: ResourceName:mlnx_sriov_rdma DeviceType:netDevice Selectors:0xc00000cd68 SelectorObj:0xc0002d1860}]
I0506 16:33:56.758711       1 manager.go:200] validating resource name "intel.com/intel_sriov_netdevice"
I0506 16:33:56.758726       1 manager.go:200] validating resource name "intel.com/intel_sriov_dpdk"
I0506 16:33:56.758736       1 manager.go:200] validating resource name "intel.com/mlnx_sriov_rdma"
I0506 16:33:56.758740       1 main.go:60] Discovering host devices
I0506 16:33:56.838173       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:01:00.0	02          	Broadcom Inc. and...	BCM57414 NetXtreme-E 10Gb/25Gb RDMA E...
I0506 16:33:56.838413       1 netDeviceProvider.go:123] excluding interface enp1s0f0np0:  default route found: {Ifindex: 3 Dst: <nil> Src: 128.110.218.251 Gw: 128.110.216.1 Flags: [] Table: 254 Realm: 0}
I0506 16:33:56.838466       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:01:00.1	02          	Broadcom Inc. and...	BCM57414 NetXtreme-E 10Gb/25Gb RDMA E...
I0506 16:33:56.838562       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.0	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex]
I0506 16:33:56.840285       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.1	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex]
I0506 16:33:56.842066       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.2	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.842193       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.3	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.842299       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.4	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.842398       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.5	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.842509       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.6	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.842596       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.7	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.842692       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:01.0	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.842788       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:01.1	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.842878       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:01.2	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.842962       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:01.3	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843053       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:01.4	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843138       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:01.5	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843221       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:01.6	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843309       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:01.7	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843396       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:02.0	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843482       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:02.1	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843574       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:02.2	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843660       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:02.3	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843743       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:02.4	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843823       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:02.5	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.843903       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:02.6	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844001       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:02.7	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844079       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:03.0	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844166       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:03.1	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844253       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:03.2	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844331       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:03.3	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844414       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:03.4	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844497       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:03.5	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844577       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:03.6	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844658       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:03.7	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844736       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:04.0	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844831       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:04.1	02          	Mellanox Technolo...	MT28800 Family [ConnectX-5 Ex Virtual...
I0506 16:33:56.844923       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:c1:00.0	02          	Broadcom Inc. and...	NetXtreme BCM5720 2-port Gigabit Ethe...
I0506 16:33:56.845014       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:c1:00.1	02          	Broadcom Inc. and...	NetXtreme BCM5720 2-port Gigabit Ethe...
I0506 16:33:56.845106       1 main.go:66] Initializing resource servers
I0506 16:33:56.845114       1 manager.go:105] number of config: 3
I0506 16:33:56.845119       1 manager.go:109]
I0506 16:33:56.845122       1 manager.go:110] Creating new ResourcePool: intel_sriov_netdevice
I0506 16:33:56.845125       1 manager.go:111] DeviceType: netDevice
I0506 16:33:56.861160       1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:c1:00.0. error getting devlink device attributes for net device 0000:c1:00.0 no such device
I0506 16:33:56.861307       1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:c1:00.1. error getting devlink device attributes for net device 0000:c1:00.1 no such device
I0506 16:33:56.861388       1 manager.go:125] no devices in device pool, skipping creating resource server for intel_sriov_netdevice
I0506 16:33:56.861393       1 manager.go:109]
I0506 16:33:56.861395       1 manager.go:110] Creating new ResourcePool: intel_sriov_dpdk
I0506 16:33:56.861398       1 manager.go:111] DeviceType: netDevice
I0506 16:33:56.877818       1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:c1:00.0. error getting devlink device attributes for net device 0000:c1:00.0 no such device
I0506 16:33:56.878647       1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:c1:00.1. error getting devlink device attributes for net device 0000:c1:00.1 no such device
I0506 16:33:56.878892       1 manager.go:125] no devices in device pool, skipping creating resource server for intel_sriov_dpdk
I0506 16:33:56.878897       1 manager.go:109]
I0506 16:33:56.878900       1 manager.go:110] Creating new ResourcePool: mlnx_sriov_rdma
I0506 16:33:56.878903       1 manager.go:111] DeviceType: netDevice
W0506 16:33:56.878928       1 pciNetDevice.go:55] RDMA resources for 0000:01:00.1 not found. Are RDMA modules loaded?
W0506 16:33:56.937793       1 pciNetDevice.go:55] RDMA resources for 0000:c1:00.0 not found. Are RDMA modules loaded?
I0506 16:33:56.937871       1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:c1:00.0. error getting devlink device attributes for net device 0000:c1:00.0 no such device
W0506 16:33:56.937931       1 pciNetDevice.go:55] RDMA resources for 0000:c1:00.1 not found. Are RDMA modules loaded?
I0506 16:33:56.938427       1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:c1:00.1. error getting devlink device attributes for net device 0000:c1:00.1 no such device
I0506 16:33:56.938673       1 manager.go:125] no devices in device pool, skipping creating resource server for mlnx_sriov_rdma
I0506 16:33:56.938681       1 main.go:72] Starting all servers...
I0506 16:33:56.938684       1 main.go:77] All servers started.
I0506 16:33:56.938687       1 main.go:78] Listening for term signals

**Comment by adrianchiris** [comment]
from logs:
```
I0506 16:33:56.878900 1 manager.go:110] Creating new ResourcePool: mlnx_sriov_rdma
I0506 16:33:56.878903 1 manager.go:111] DeviceType: netDevice
W0506 16:33:56.878928 1 pciNetDevice.go:55] RDMA resources for 0000:01:00.1 not found. Are RDMA modules loaded?
W0506 16:33:56.937793 1 pciNetDevice.go:55] RDMA resources for 0000:c1:00.0 not found. Are RDMA modules loaded?
I0506 16:33:56.937871 1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:c1:00.0. error getting devlink device attributes for net device 0000:c1:00.0 no such device
W0506 16:33:56.937931 1 pciNetDevice.go:55] RDMA resources for 0000:c1:00.1 not found. Are RDMA modules loaded?
I0506 16:33:56.938427 1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:c1:00.1. error getting devlink device attributes for net device 0000:c1:00.1 no such device
I0506 16:33:56.938673 1 manager.go:125] no devices in device pool, skipping creating resource server for mlnx_sriov_rdma
```

no devices were added to `mlnx_sriov_rdma` resource

from the resource configuration of `mlnx_sriov_rdma`, you should either provide the list of PCI device ids in `devices` selector 
or use `pciAddresses` selector instead if you want to select based on individual PCI addresses

**Comment by eduardocalfaia** [comment]
> I0506 16:33:56.838562 1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.0 02 Mellanox Technolo... MT28800 Family [ConnectX-5 Ex]
> I0506 16:33:56.840285 1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.1 02 Mellanox Technolo... MT28800 Family [ConnectX-5 Ex]
> I0506 16:33:56.842066 1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.2 02 Mellanox Technolo... MT28800 Family [ConnectX-5 Ex Virtual...
> I0506 16:33:56.842193 1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:41:00.3 02 Mellanox Technolo... MT28800 Family [ConnectX-5 Ex Virtual...

Hi Adrian,
Thanks your help

How could I do that? could you help me please? 

my piece of code is this
     {
                "resourceName": "mlnx_sriov_rdma",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1018"],
                    "drivers": ["mlx5_ib"],
                    "isRdma": true
                }

**Comment by eduardocalfaia** [comment]
> "resourceName": "mlnx_sriov_rdma",
> "selectors": {
> "vendors": ["15b3"],
> "devices": ["0000:41:00.2","0000:41:00.3","0000:41:00.4","0000:41:00.5","0000:41:00.6","0000:41:00.7"],
> "drivers": ["mlx5_ib"],
> "isRdma": true

I put this before but it didn't work.

**Comment by adrianchiris** [comment]
I now noticed you are using ConnectX5 Ex.

ConnectX5 Ex virtual function device id is "101a" and not "1018" (which is ConnectX 5 virtual function device ID)

can you try changing devices selector to : `"devices": ["101a"],` ?
and also remove the drivers selector, you should not need it.

in addition, the bound driver is "mlx5_core" and not "mlx5_ib"

**Comment by eduardocalfaia** [comment]
> I now noticed you are using ConnectX5 Ex.
> 
> ConnectX5 Ex virtual function device id is "101a" and not "1018" (which is ConnectX 5 virtual function device ID)
> 
> can you try changing devices selector to : `"devices": ["101a"],` ? and also remove the drivers selector, you should not need it.
> 
> in addition, the bound driver is "mlx5_core" and not "mlx5_ib"
> 
> e.g
> 
> ```
> {
> "resourceName": "mlnx_sriov_rdma",
> "selectors": {
> "vendors": ["15b3"],
> "devices": ["101a"],
> "isRdma": true
> }
> ```

It works, thank you very much @adrianchiris

**Comment by adrianchiris** [comment]
Happy to hear that. closing this issue then.
