### ISSUE TITLE
Release SR-IOV network device plugin 3.5.0

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-network-device-plugin#428]
It has been a while since we released a new version on SRIOV network device plugin.

https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/compare/v3.4.0...master

If there is anything else you would like to get in, please comment :)

ideally, i would like to converge on release in a couple of weeks.

**Comment by chandanD4** [comment]
@adrianchiris  : Do we have any ETA on this .

**Comment by adrianchiris** [comment]
seems like no additional requests for release. proceeding with release then.
