### ISSUE TITLE
Supporting Probe for sriov-network-device-plugin

### ISSUE THREAD

**Issue by chandanD4** [k8snetworkplumbingwg/sriov-network-device-plugin#432]
## What would you like to be added?

liveness probe support 

## What is the use case for this feature / enhancement?

Many applications running for long periods of time may eventually or eventually transition to broken states, and cannot recover except by being restarted. Kubernetes provides liveness probes to detect and remedy such situations.  This is required for cluster to operate in healthy state.

**Comment by chandanD4** [comment]
I had quick check on this , but unfortunately we did n't had any stuck situation in past.  This request is more from monitoring aspect and proactive detection of any such situation.

**Comment by SchSeba** [comment]
was implemented https://github.com/k8snetworkplumbingwg/network-resources-injector/pull/125

closing this issue
