### ISSUE TITLE
Add ability to select devices based on NIC names

### ISSUE THREAD

**Issue by ian-howell** [k8snetworkplumbingwg/sriov-network-device-plugin#433]
## What would you like to be added?

I would like to be able to create configmaps which allow for the sriov-device-plugin to select NICs based on their names, e.g.

```
{
    "resourceList": [{
            "resourceName": "sriov_netdevice",
            "selectors": {
                "nicNames": ["net1", "net2"]
            }
        }
}
```

## What is the use case for this feature / enhancement?

This is useful when creating a device in libvirt, as the targets for the current selectors are unknown at VM creation time.

**Comment by ian-howell** [comment]
I'm generating the SRIOV-DP configmap prior to the creation of any VMs. In my case, I'm creating a VM template which is then used by kubevirt to later generate the actual VM. Even though I could specify a pci address for the device in the template, libvirt doesn't guarantee that the resulting device will actually get that address ([libvirt docs](https://libvirt.org/pci-addresses.html)). However, that isn't the case for other device info such as NIC name or MAC address

**Comment by ian-howell** [comment]
@SchSeba Any updates on this?

**Comment by SchSeba** [comment]
@ian-howell Thanks for the info!

**Comment by SchSeba** [comment]
Hi @ian-howell 

can you please have a look on this links and let me know if that solve your use case

https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/
https://github.com/kubevirt/kubevirt/blob/main/docs/sriov.md
https://dougbtv.com/nfvpe/2019/05/15/kubevirt-sriov/

**Comment by SchSeba** [comment]
Hi @ian-howell can we close this isse?

**Comment by ian-howell** [comment]
Hey @SchSeba, after some investigation, I've found that the pfNames selector isn't sufficient for our use cases. I need to be able to target the device as it is named within the VM.

**Comment by SchSeba** [comment]
closing this one as we implement the ACPI instead https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/488
