### ISSUE TITLE
Broadcom Instructions

### ISSUE THREAD

**Issue by thisab** [k8snetworkplumbingwg/sriov-network-device-plugin#449]
We have a Broadcom NIC that we wish had more instructions on how to properly configure devices for this manufacturer. (If possible :) )

Looking back there is a previous request https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/274
that mentions that it could work.

However we are trying SR-IOV with a BCM57416, and the instruction says:
Make sure to update the 'config.json' entry in the configMap data to reflect your resource configuration for the device plugin. See [Configurations](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin#configurations) section for supported configuration parameters.

But there is no Broadcom listed in the configuration parameters.

How can we modify it to support this NIC?

**Comment by adrianchiris** [comment]
Greetings !

when configuring sriov-network-device-plugin resource pool you need to provide selectors that would match your target NIC's VFs.

the type of selectors are documented in the configuration section you added a link to.

e.g by specifying `vendor` and device selectors (with broadcom's PCI vendor ID and VF PCI device ID) or with `pfNames` selector specifing the physical function netdev.

**Comment by thisab** [comment]
Hello @adrianchiris ,
Thanks for the fast response.

I see that "resourceName" is a required paramenter. 
As there is no broadcom listed, we do not know which one to use.

**Comment by SchSeba** [comment]
Hi @thisab any update on this?

**Comment by thisab** [comment]
Hi @SchSeba,

Yes we were able to successfully use the Broadcom interfaces using the instructions above.
For anyone that would like in the future:

`      "resourceList": [
        {
            "resourceName": "broadcom_sriov_vfdevice",
            "resourcePrefix": "broadcom.com",
            "selectors": {
                "vendors": ["14e4"],
                "devices": ["16dc"],
                "drivers": ["bnxt_en"]
            }
        }
`

Therefore, I will be closing this case.
