### ISSUE TITLE
Pods using sriov vf bound to vfio-pci driver fail post a host reboot since pci address to /dev/vfio/iommu_group changes across reboots

### ISSUE THREAD

**Issue by lchimbili** [k8snetworkplumbingwg/sriov-network-device-plugin#451]
### What happened?
Upon reboot, Pods using sriov vf bound to vfio-pci driver fail to come up
### What did you expect to happen?
Pods should come up successfully
### What are the minimal steps needed to reproduce the bug?
1. Create a pod which requests sriov vf bound to vfio-pci driver
2. Reboot the host
3. (a) Pod either goes into error state with an error like below,
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      error gathering device information while adding custom device "/dev/vfio/100": no such file or directory
   (b) or Pod comes up but the sriov vf is unusable since the corresponding /dev/vfio/<iommu group number> is not mounted inside the pod
   [test-pod /]# readlink /sys/bus/pci/devices/0000:89:05.2/iommu_group
                        ../../../../kernel/iommu_groups/125
   [test-pod /]# ls -l /dev/vfio/125
                         ls: cannot access /dev/vfio/125: No such file or directory
   
### Anything else we need to know?
It appears that the SRIOV VF device pci address <-> /dev/vfio/<iommu group number> mapping keeps changing on reboot of the node.

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |3.4.0|
|SR-IOV CNI Plugin            |2.6.2|
|Multus                       |3.8|
|Kubernetes                   |v1.22.2| 
|OS                           |RHEL 8.6|

### Config Files
Config file locations may be config dependent.

##### Multus config (Try '/etc/cni/multus/net.d')
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "capabilities": {"portMappings": true, "bandwidth": true}, "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "k8s-pod-network", "cniVersion": "0.3.1", "plugins": [ { "type": "calico", "datastore_type": "kubernetes", "mtu": 9000, "nodename_file_optional": false, "log_level": "Info", "log_file_path": "/var/log/calico/cni/cni.log", "ipam": { "type": "calico-ipam", "assign_ipv4" : "false", "assign_ipv6" : "true"}, "container_settings": { "allow_ip_forwarding": false }, "policy": { "type": "k8s" }, "kubernetes": { "k8s_api_root":"https://[fd33:ca9b:3a09:868d::1]:443", "kubeconfig": "/etc/cni/net.d/calico-kubeconfig" } }, { "type": "bandwidth", "capabilities": {"bandwidth": true} }, {"type": "portmap", "snat": true, "capabilities": {"portMappings": true}} ] } ] }

##### Kubernetes deployment type ( Bare Metal, Kubeadm etc.)
Kubeadm
##### SR-IOV Network Custom Resource Definition
Not applicable
### Logs
**Before Node reboot:
==================**
# kubectl exec -it test-sriov-vlan-interface-pod4 -- bash
[root@test-sriov-vlan-interface-pod4 /]# env | grep -i pci
PCIDEVICE_RS_COM_FH_CUPLANE_P4=0000:89:05.2
[root@test-sriov-vlan-interface-pod4 /]# readlink /sys/bus/pci/devices/0000:89:05.2/iommu_group
../../../../kernel/iommu_groups/122
**[root@test-sriov-vlan-interface-pod4 /]# ls -l /dev/vfio/122
crw------- 1 root root 239, 10 Nov 10 11:46 /dev/vfio/122**

**After Node reboot:
==================**
# kubectl exec -it test-sriov-vlan-interface-pod4 -- bash
[root@test-sriov-vlan-interface-pod4 /]# env | grep -i pci
PCIDEVICE_RS_COM_FH_CUPLANE_P4=0000:89:05.2
[root@test-sriov-vlan-interface-pod4 /]# readlink /sys/bus/pci/devices/0000:89:05.2/iommu_group
../../../../kernel/iommu_groups/125
**[root@test-sriov-vlan-interface-pod4 /]# ls -l /dev/vfio/125
ls: cannot access /dev/vfio/125: No such file or directory**
[root@test-sriov-vlan-interface-pod4 /]# ls -l /dev/vfio/
total 0
crw------- 1 root root 239,  12 Nov 10 12:05 122
crw------- 1 root root 239,   4 Nov 10 12:05 136
crw-rw-rw- 1 root root  10, 196 Nov 10 12:05 vfio

**Docker Inspect output:
===============**
"Devices": [
	{
		"PathOnHost": "/dev/vfio/vfio",
		"PathInContainer": "/dev/vfio/vfio",
		"CgroupPermissions": "mrw"
	},
	{
		"PathOnHost": "/dev/vfio/136",
		"PathInContainer": "/dev/vfio/136",
		"CgroupPermissions": "mrw"
	},
	{
		**"PathOnHost": "/dev/vfio/122",
		"PathInContainer": "/dev/vfio/122",
		"CgroupPermissions": "mrw"**
	}
],

**Comment by SchSeba** [comment]
Hi @lchimbili question is the pod deleted and recreated on the reboot, the eviction time is lower then the time takes the node to reboot?

if not it may be this issue in k8s https://github.com/kubernetes/kubernetes/issues/109595
to test it can you create a systemd service that will run before kubelet and will remove the checkpoint file?

```
/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint
```

**Comment by SchSeba** [comment]
also please share the `cat /proc/cmdline` to see if there is anything in the kernel parameters that can create this issue

**Comment by lchimbili** [comment]
Hello @SchSeba,

Removing the file /var/lib/kubelet/device-plugins/kubelet_internal_checkpoint before kubelet starts running solved this issue.
Thank you very much for the advice.

Best Regards

**Comment by SchSeba** [comment]
This is a w/a until Kubernetes fix the issue.

I will close this issue feel free to reopen if needed
