### ISSUE TITLE
Update depencency to govdpa v.0.1.4

### ISSUE THREAD

**Issue by lmilleri** [k8snetworkplumbingwg/sriov-network-device-plugin#452]
## What issue would you like to bring attention to?
Release v0.1.4 has been published for [govdpa](https://github.com/k8snetworkplumbingwg/govdpa) library, introducing new capabilities like add/remove a vdpa device, code refactoring, etc.
It is recommended to update the sriov-network-device-plugin dependency to govdpa v0.1.4.

## What is the impact of this issue?
No big impact, just some minor changes are required to adapt to the new govdpa public interface

## Do you have a proposed response or remediation for the issue?
PR has been submitted for review: https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/450

**Comment by SchSeba** [comment]
closing this issue as the PR is merged
