### ISSUE TITLE
sriov-network-device-plugin fails to build image

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-network-device-plugin#459]
### What happened?

build push image job is failing:
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/actions/runs/3866251321/jobs/6590255842

also please note that currently we are only compiling ddptool for amd64 arch only. is that OK ? or we want to add for other archs as well ?

```
#17 [builder 8/8] RUN make
#0 0.060 gcc -fstack-protector -fPIE -fPIC -Wformat -Wformat-security -Wall -fno-delete-null-pointer-checks -fno-strict-overflow -fwrapv -O2 -D_FORTIFY_SOURCE=2 -Werror -Wl,-strip-debug -I./inc -I./src -I./devlink_module/src   -c -o src/ddp.o src/ddp.c
#0 0.089 src/ddp.c: In function 'execute_adminq_command':
#17 0.089 src/ddp.c:350:51: error: the comparison will always evaluate as 'false' for the address of 'data' will never be NULL [-Werror=address]
#17 0.089   350 |         if(ioctl_data == NULL || ioctl_data->data == NULL)
#17 0.089       |                                                   ^~
#17 0.090 In file included from ./inc/ddp.h:55,
#17 0.090                  from src/ddp.c:31:
#17 0.090 ./inc/ddp_types.h:123:14: note: 'data' declared here
#17 0.090   123 |     uint8_t  data[1];      /* reserved memory for pointer for buffer */
#17 0.090       |              ^~~~
#17 0.090 src/ddp.c: In function 'write_register':
#17 0.091 src/ddp.c:419:51: error: the comparison will always evaluate as 'false' for the address of 'data' will never be NULL [-Werror=address]
#17 0.091   419 |         if(ioctl_data == NULL || ioctl_data->data == NULL)
#17 0.091       |                                                   ^~
#17 0.091 ./inc/ddp_types.h:123:14: note: 'data' declared here
#17 0.091   123 |     uint8_t  data[1];      /* reserved memory for pointer for buffer */
#17 0.091       |              ^~~~
#17 0.091 src/ddp.c: In function 'read_register':
#17 0.091 src/ddp.c:494:51: error: the comparison will always evaluate as 'false' for the address of 'data' will never be NULL [-Werror=address]
#17 0.091   494 |         if(ioctl_data == NULL || ioctl_data->data == NULL)
#17 0.091       |                                                   ^~
#17 0.091 ./inc/ddp_types.h:123:14: note: 'data' declared here
#17 0.091   123 |     uint8_t  data[1];      /* reserved memory for pointer for buffer */
#17 0.091       |              ^~~~
#17 0.290 cc1: all warnings being treated as errors
#17 0.292 make: *** [<builtin>: src/ddp.o] Error 1
#17 ERROR: process "/bin/sh -c make" did not complete successfully: exit code: 2
```

probably due to newer gcc in alpine image (just an assumption, i didnt validate it)

### What did you expect to happen?

CI step to complete successfully

### What are the minimal steps needed to reproduce the bug?

run make image 

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<Input Version Here>|
|SR-IOV CNI Plugin            |<Input Version Here>|
|Multus                       |<Input Version Here>|
|Kubernetes                   |<Input Version Here>| 
|OS                           |<Input Version Here>|

### Config Files
Config file locations may be config dependent.

**Comment by adrianchiris** [comment]
@Eoghan1232 PTAL

if we can get this fixed soon it would be great

**Comment by Eoghan1232** [comment]
Hi @adrianchiris,

Looks like golang:1.18-alpine has moved from:
``alpine 3.16 -> 3.17`` as of Nov 22.
which has updated the gcc from : 
``11.2.1_git20220219-r2 -> 12.2.1_git20220924-r4`` and a couple other dependencies, which is now breaking the image build

for now, I suggest we disable the image build process until we can fix the build issue.
or a quick fix for now, is to just simply tag the image version as ``1.18-alpine3.16`` [(link)](https://github.com/docker-library/golang/blob/6bf11786153a087ebfb866ac9417c4381b30df8f/1.18/alpine3.16/Dockerfile) instead of just 1.18-alpine. (tested locally and this worked)
WDYT?

also, @SchSeba, I believe you had this issue locally already right ?

**Comment by SchSeba** [comment]
@Eoghan1232 yep this is the same issue we spoke offline

**Comment by SchSeba** [comment]
The issue was fixed https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/463
