### ISSUE TITLE
Why do we not allow to have "-" and "." in the resourceName

### ISSUE THREAD

**Issue by liuyuan10** [k8snetworkplumbingwg/sriov-network-device-plugin#476]
## What issue would you like to bring attention to?
I see we enforce this regex on the resource name here https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/master/pkg/utils/utils.go#L276

which is more restricted than k8s object name.

What's missing is "-" and "." which is allowed in the k8s object name but not allowed with this regex.

## What is the impact of this issue?

It makes it hard to auto generate resource name from other k8s object name.

## Do you have a proposed response or remediation for the issue?
Fix the regex if it's not needed (adding "-" and ".")

**Comment by adrianchiris** [comment]
Hi,

as you know k8s resource name are following similar to the following:
`example.com/someResource`
` example.com/special-resource`
` other-example.com/special-resource`

the validation in question on validates the string after `/`
so allowing `.` would yield a invalid resource name in k8s IMO (i did not try it) so i may be wrong here

e.g
`example.com/some.resource`


another point to take into account is that we expose the resource name as env variable, converting "special" chars to underscore in [1]

supporting `-` and `.` would lead to ambiguity if we do the same conversion or end up with "inconsistent" env var names

[1] https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/2897303a0d262610a0bf56d5de97acf796a3b3f7/pkg/resources/pool_stub.go#L120

**Comment by liuyuan10** [comment]
> so allowing . would yield a invalid resource name in k8s IMO (i did not try it) so i may be wrong here

We've tried "dot" is a valid resource name from kubelet view

> supporting - and . would lead to ambiguity if we do the same conversion or end up with "inconsistent" env var names

It's not clear to me. the device plugin today anyway allow "-" and "." in the prefix, which goes into the env var. Doesn't such "inconsistence" already present?

I can see some change is needed to allow "-" and "." but just wondering if there is really technical reason we are being more restrict than k8s

**Comment by adrianchiris** [comment]
> We've tried "dot" is a valid resource name from kubelet view

looking at device plugin proto, it says it should be a _DNS label_ [1] so we cant put dots in resource name.

> It's not clear to me. the device plugin today anyway allow "-" and "." in the prefix, which goes into the env var. Doesn't such "inconsistence" already present?

indeed, we should fix this.

> I can see some change is needed to allow "-" and "." but just wondering if there is really technical reason we are being more restrict than k8s

no technical reason that im aware. im ok to support "-". 

[1] https://github.com/kubernetes/kubernetes/blob/b1f901acf44f8adf69759db434690c2a8bdd616b/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/api.proto#L41
