### ISSUE TITLE
Release 3.6.0

### ISSUE THREAD

**Issue by Eoghan1232** [k8snetworkplumbingwg/sriov-network-device-plugin#486]
The last release was v3.5.1 which was July 4th, 2022.

Should we look to release again?

My wish list to get merged for the release:
#475 
#443 
#387 

any other PR's to consider?

**Comment by adrianchiris** [comment]
@Eoghan1232 shall we proceed with release ? if the remaining PRs are merged we can do another release

**Comment by Eoghan1232** [comment]
Yes sounds good to me.

**Comment by zeeke** [comment]
Looks go to me too

**Comment by Eoghan1232** [comment]
I see we released, I will close this issue and reopen a new one at a later date once we want to release again.
