### ISSUE TITLE
Wrong DeviceInfo file content for vhost-vdpa devices

### ISSUE THREAD

**Issue by lmilleri** [k8snetworkplumbingwg/sriov-network-device-plugin#492]
### What happened?
DeviceInfo file content (in directory /var/run/k8s.cni.cncf.io/devinfo/dp/) for vhost-vdpa devices is not generated properly.

### What did you expect to happen?
Wrong DeviceInfo (the **path** is not correct):
```
{
  "type": "vdpa",
  "version": "1.0.0",
  "vdpa": {
    "parent-device": "vdpa:0000:65:00.3",
    "driver": "vhost",
    "path": "pci/0000:65:00.3",
    "pci-address": "0000:65:00.3"
  }
}
```
Expected DeviceInfo:
```
{
  "type": "vdpa",
  "version": "1.0.0",
  "vdpa": {
    "parent-device": "vdpa:0000:65:00.3",
    "driver": "vhost",
    "path": "/dev/vhost-vdpa-0",
    "pci-address": "0000:65:00.3"
  }
}
```

### What are the minimal steps needed to reproduce the bug?
- Setup an OCP cluster with at least one BM worker. Also an NVIDIA Connect-6 DX card is present in the system
- Partition the NIC into VFs with SRIOV and create vhost-vdpa devices on top of VFs (switchdev mode and OVS HW offload enabled)
- Deploy the sriov-network-device-plugin
- apply DP config map like in this example:
```
{
  "resourceList": [
    {
      "resourceName": "mlxnics",
      "selectors": {
        "vendors": [
          "15b3"
        ],
        "devices": [
          "101e"
        ],
        "rootDevices": [
          "0000:65:00.0"
        ],
        "IsRdma": false,
        "NeedVhostNet": false,
        "vdpaType": "vhost"
      },
      "SelectorObj": null
    }
  ]
}
```

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |latest|
|SR-IOV CNI Plugin            |Not applicable, using ovn-kubernetes|
|Multus                       |OCP 4.13|
|Kubernetes                   |OCP 4.13| 
|OS                           |Linux virtlab711.virt.lab.eng.bos.redhat.com 5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 31 10:39:18 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux|

### Config Files
Config file locations may be config dependent.

**Comment by SchSeba** [comment]
closing this one
