### ISSUE TITLE
Is there a way to configure vlan id on pf or vf of sriov ?

### ISSUE THREAD

**Issue by bobz965** [k8snetworkplumbingwg/sriov-network-device-plugin#498]
Hi, i have a question, Is there a way to configure vlan id on pf or vf of sriov ?

**Comment by SchSeba** [comment]
for PF you will need to create a vlan interface on the host that is out of the scope of the sriov operator.
you can have something like k-nmstate operator for that.

about the VFs that is possible when we allocate the vf to a pod you allocate a vlan but that is part of the sriov-cni not the sriov-device plugin

https://github.com/k8snetworkplumbingwg/sriov-cni

**Comment by bobz965** [comment]
Thank you @SchSeba
