### ISSUE TITLE
DDP Tool failing to get ddp profile for devices

### ISSUE THREAD

**Issue by Eoghan1232** [k8snetworkplumbingwg/sriov-network-device-plugin#516]
### What happened?
Deploy DP from main with configMap specifying DDP Profile
Device did not get picked up 

In the code, I can see we run it as ``cmd := ddpExecCommand("ddptool", "-l", "-a", "-j", "-s", dev)``

I ran ddptool inside of DP container with this flag and you can see it returned error 5, which is what showed in DP logs.

I ran against PCI Address instead and got the DDP profile. 

```
/ # ddptool
Intel(R) Dynamic Device Personalization Tool
DDPTool version 1.0.1.12
Copyright (C) 2019 - 2021 Intel Corporation.

NIC  DevId D:B:S.F      DevName         TrackId  Version      Name
==== ===== ============ =============== ======== ============ ==============================
001) 158B  0000:18:00.1 enp24s0f1       -        -            No profile loaded
002) 1592  0000:AF:00.0 enp175s0np0     0        1.3.10.0     ICE Wireless Edge Package
003) 1592  0000:B2:00.0 enp178s0np0     0        1.3.26.0     ICE OS Default Package
/ # ddptool -l -a -j -s enp175s0np0
{"DDPInventory":{
                "error": "5"
                "message": "No driver available"
        }
}
/ # ddptool -l -a -j -s 0000:AF:00.0
{
        "DDPInventory": {
                "device": "1592",
                "address": "0000:AF:00.0",
                "name": "enp175s0np0",
                "display": "Intel(R) Ethernet Network Adapter E810-2C-Q2",
                "DDPpackage": {
                        "track_id": "0",
                        "version": "1.3.10.0",
                        "name": "ICE Wireless Edge Package"
                }
        }
}
```

### What are the minimal steps needed to reproduce the bug?
Just deploy from main

Seems to be a bug with DDP Tool? we pass the pci address to the PCI.

**Comment by Eoghan1232** [comment]
I can see we do pass the pci address, so not sure why it's not working. it should work.

**Comment by Eoghan1232** [comment]
```
/ # /usr/bin/ddptool -l -a -j -s 0000:AF:00.0
{
        "DDPInventory": {
                "device": "1592",
                "address": "0000:AF:00.0",
                "name": "enp175s0np0",
                "display": "Intel(R) Ethernet Network Adapter E810-2C-Q2",
                "DDPpackage": {
                        "track_id": "0",
                        "version": "1.3.10.0",
                        "name": "ICE Wireless Edge Package"
                }
        }
}
/ #
```

I checked the full cmd, and it failed but looked valid.
I ran the exact cmd inside of pod, and this worked.

**Comment by SchSeba** [comment]
I was never in favor of using that ddp tool :(
if you can resume the work that was done here https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/387 it will be great to have a single valid interface to use ddp without the need for external programs

**Comment by Eoghan1232** [comment]
> I was never in favor of using that ddp tool :( if you can resume the work that was done here #387 it will be great to have a single valid interface to use ddp without the need for external programs

Yes - although I don't think the netlink pkg will work with FVL cards - so it needs to be tested. will set something up internally for this validation.

**Comment by SchSeba** [comment]
oh you maybe right :(
so maybe in https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/387 we can have a fallback to this file and lets have a fix for the running of the ddp tool

**Comment by Eoghan1232** [comment]
I've updated #387

I also checked ddp-tool, and tried the latest version - it does not work against VF's
I've created a bug for that team to fix the issue, I will create separate PR to update ddp-tool version once it's ready and validated.

**Comment by SchSeba** [comment]
Hi @Eoghan1232 any update on the DDP tool?

**Comment by Eoghan1232** [comment]
Hey @SchSeba so they only recently got back to me, and seems the latest version of DDP works, I need to retest this and update the version we use in the repo 
Possibly they need to release the version they tested with as it doesn't seem to be public.
Also the version of ice driver may matter, so I will see if there is docs on the min supported version, etc and update our readMe

**Comment by SchSeba** [comment]
I am closing this one we already have support for devlink API instead of this DDP tool
