### ISSUE TITLE
For sriovdp can you please add the cleanup period like when ever it reaches max no of files

### ISSUE THREAD

**Issue by hemanth18-web** [k8snetworkplumbingwg/sriov-network-device-plugin#520]
## What would you like to be added?
For sriovdp can you please add the cleanup period like when ever it reaches the max no of files or max size  it will automatically cleanup the files

**Comment by SchSeba** [comment]
Hi @hemanth18-web I don't understand the request can you please explain?

**Comment by SchSeba** [comment]
@hemanth18-web no comments closing this one feel free to reopen if needed
