### ISSUE TITLE
Setting up more than 16 Virtual Functions

### ISSUE THREAD

**Issue by vahsek300501** [k8snetworkplumbingwg/sriov-network-device-plugin#536]
I am setting up virtual functions as described in the documentation for Mellanox Connect X7 series. I want to create 24 Virtual function for the network adapter. But when try to setup the `sriov_numfs` param it gives out an error. I tried doing this 

`echo 0 > /sys/class/net/enp2s0f0/device/sriov_numvfs` 
`echo 24 > /sys/class/net/enp2s0f0/device/sriov_numvfs`

There is a maxvfs file in the same directory which has the value 16. When I try to create 16 VFS it succeeds but I am unable to edit that file as it is read-only file.

Can someone please help.

Thanks

**Comment by SchSeba** [comment]
This is not related to the sriov-network-device-plugin but please take a look on the mstconfig from MLX and see what is the max number of virtual functions the hardware supports

**Comment by vahsek300501** [comment]
Thanks. Closing the issue.
