### ISSUE TITLE
feature: support for CDI

### ISSUE THREAD

**Issue by cyclinder** [k8snetworkplumbingwg/sriov-network-device-plugin#539]
## What would you like to be added?

[CDI](https://github.com/cncf-tags/container-device-interface) (Container Device Interface), is a [specification](https://github.com/cncf-tags/container-device-interface/blob/main/SPEC.md), for container-runtimes, to support third-party devices.

It introduces an abstract notion of a device as a resource. Such devices are uniquely specified by a fully-qualified name that is constructed from a vendor ID, a device class, and a name that is unique per vendor ID-device class pair.

## What is the use case for this feature / enhancement?

Refer to https://github.com/Mellanox/k8s-rdma-shared-dev-plugin/pull/77

**Comment by adrianchiris** [comment]
Hi @cyclinder , please see: https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/master/deployments/cdi/README.md

**Comment by cyclinder** [comment]
Thanks @adrianchiris, I didn't notice it, let me close it now.
