### ISSUE TITLE
Get rid of vendoring

### ISSUE THREAD

**Issue by jaypipes** [k8snetworkplumbingwg/sriov-network-device-plugin#544]
Hi! I'm wondering if you would be OK with a pull request that removes the `vendor/` directory and uses only Go modules for dependency management?

We (Microsoft Network Cloud) have a mirror of this repo internally for software supply chain purposes and the vendor/ directory makes the mirror maintenance unnecessarily painful. Modern Go and modules are a cleaner, more maintainable way to manage dependencies...

**Comment by adrianchiris** [comment]
Hi @jaypipes, im ok with this change.

@SchSeba @Eoghan1232 WDYT?

i dont remember if for openshift this is needed.

**Comment by Eoghan1232** [comment]
I am happy for it to go :) 
but afaik, it's a requirement on the RH side? @SchSeba

**Comment by jaypipes** [comment]
@ffromani what say you, Red Hatter? :)

Also, Francesco, I'll be submitting similar PRs to remove vendoring from all the topologyawarewg repos!

**Comment by zeeke** [comment]
Looks good to me!

We already have examples of upstream-no-vendor/downstream-vendored projects.
(https://github.com/metallb/metallb-operator / https://github.com/openshift/metallb-operator).

Getting rid of the vendor folder in `opeshift/*` forks requires a little more work (don't have all the details ATM) to adjust the delivery pipeline, but it can be unrelated to this repository

**Comment by jaypipes** [comment]
@bn222 @zeeke hello! Any chance I can get reviews on the two PRs submitted that remove vendoring from multus-cni and sriov-network-device-plugin? Thanks much in advance! :)

**Comment by SchSeba** [comment]
closing https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/548
