### ISSUE TITLE
can not create CDI json

### ISSUE THREAD

**Issue by cyclinder** [k8snetworkplumbingwg/sriov-network-device-plugin#546]
### What happened?

```
E0314 08:44:33.830924       1 cdi.go:85] CreateCDISpecForPool(): can not create CDI json: invalid CDI Spec: failed add device "0000:af:02.0": invalid device, empty device edits
E0314 08:44:33.830950       1 server.go:217] updateCDISpec(): error creating CDI spec: invalid CDI Spec: failed add device "0000:af:02.0": invalid device, empty device edits
E0314 08:44:33.830966       1 server.go:167] can't update CDI specs: invalid CDI Spec: failed add device "0000:af:02.0": invalid device, empty device edits
```

### What did you expect to happen?

It able to create CDI json

### What are the minimal steps needed to reproduce the bug?

1. install sriov-operator with the master branch
2. edit sriovoperatorconfig: added useCDI to true
3. create sriovnetworknodepolicy 

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<Input Version Here>|
|SR-IOV CNI Plugin            |<Input Version Here>|
|Multus                       |<Input Version Here>|
|Kubernetes                   |<Input Version Here>| 
|OS                           |<Input Version Here>|

### Config Files
Config file locations may be config dependent.

**Comment by SchSeba** [comment]
Hi @e0ne will you be able to take a look?

**Comment by SchSeba** [comment]
Hi @cyclinder is this still an issue?

**Comment by SchSeba** [comment]
closing
