### ISSUE TITLE
Does this plug-in support vfio pci accelerators that are not network in nature?

### ISSUE THREAD

**Issue by gaure** [k8snetworkplumbingwg/sriov-network-device-plugin#597]
## What issue would you like to bring attention to?
Not an issue

## What is the impact of this issue?
None

## Do you have a proposed response or remediation for the issue?
NA

## Question
I have a PCI card that uses the kernel VFIO driver, will this plug-in detect such PCI card even if it is not a network card?

**Comment by gaure** [comment]
No response

**Comment by SchSeba** [comment]
Hi sorry for the late replay
if you are still around :)

the device plugin support 3  type of devices Networks , Accelerators  and axillary
you can see the list here 

https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/15364062083cdc24a75cfa71a471e276c1048458/pkg/types/types.go#L82

**Comment by gaure** [comment]
Thanks @SchSeba
