### ISSUE TITLE
Monitor health for userspace devices

### ISSUE THREAD

**Issue by booxter** [k8snetworkplumbingwg/sriov-network-device-plugin#89]
Code inspection suggests that userspace devices like of ```vfio``` type never switch their health state https://github.com/intel/sriov-network-device-plugin/blob/db45dc4a722daf895d8c24fc91d99dde86c10c57/pkg/resources/vfioPool.go#L100 so they can never become unhealthy regardless of what may have happened to their corresponding PFs. I believe we should monitor health for ```vfio``` devices by monitoring their PFs.

**Comment by booxter** [comment]
@greg-bock for the record I've created this bug to track health checks for ```vfio``` devices (as per our discussion in ```kubevirt``` context).

**Comment by greg-bock** [comment]
A coworker and I had discussed new types for other reasons but it might make sense here too. Not all vfio devices are necessarily network devices. I wonder if this should be a new resource type or maybe extend the vfioResourcePool type to include an optional function (e.g. netdevice) so it knows how, if at all, to do health checks.

**Comment by ahalim-intel** [comment]
We are planning to adopt a [netlink ](https://godoc.org/github.com/vishvananda/netlink) based link status watcher(only applicable to network devices) in which when a PF link status changes, the corresponding VFs health status will be updated accordingly.  I know vfio devices are not limited to network devices only, but with sriov-network-device plugin we are only concerned about network devices here.

**Comment by zshi-redhat** [comment]
@greg-bock as Abdul mentioned in above comment, this project is for network device only, especially SR-IOV, we didn't consider extend the scope to support other types of devices yet. but it's good to hear that this framework may also be applicable to other devices.

@booxter for the original issue reported, do you think that it's enough to monitor the PF to get healthy state of each VF(whether it's netdevice or vfio) attached? I'd like to label this as a feature enhancement per the discussion(adopt a netlink based link status watcher) yesterday in resource management meeting.

**Comment by booxter** [comment]
@zshi-redhat I think it's fair to say PF status is VF status. (Unless a card exposes some additional health state, which I understand is not common or existing.)

**Comment by killianmuldoon** [comment]
@booxter We don't have any health checks implemented right now - do you think we could come up with a reasonable way to assert the health of all devices? Without being able to use state=down this is a tough problem.

**Comment by martinkennelly** [comment]
Closing due to being stale.
